export interface TickerEntry {
  ticker: string
  expectedName: string
  indices: string[]
}

// ─── CAC 40 (40 values) ───
const CAC40: TickerEntry[] = [
  { ticker: "AC.PA", expectedName: "Accor", indices: ["CAC 40"] },
  { ticker: "AI.PA", expectedName: "Air Liquide", indices: ["CAC 40"] },
  { ticker: "AIR.PA", expectedName: "Airbus", indices: ["CAC 40"] },
  { ticker: "ALO.PA", expectedName: "Alstom", indices: ["CAC 40"] },
  { ticker: "MT.PA", expectedName: "ArcelorMittal", indices: ["CAC 40"] },
  { ticker: "CS.PA", expectedName: "AXA", indices: ["CAC 40"] },
  { ticker: "BNP.PA", expectedName: "BNP Paribas", indices: ["CAC 40"] },
  { ticker: "EN.PA", expectedName: "Bouygues", indices: ["CAC 40"] },
  { ticker: "CAP.PA", expectedName: "Capgemini", indices: ["CAC 40"] },
  { ticker: "CA.PA", expectedName: "Carrefour", indices: ["CAC 40"] },
  { ticker: "ACA.PA", expectedName: "Crédit Agricole", indices: ["CAC 40"] },
  { ticker: "BN.PA", expectedName: "Danone", indices: ["CAC 40"] },
  { ticker: "DSY.PA", expectedName: "Dassault Systèmes", indices: ["CAC 40"] },
  { ticker: "ENGI.PA", expectedName: "Engie", indices: ["CAC 40"] },
  { ticker: "EL.PA", expectedName: "EssilorLuxottica", indices: ["CAC 40"] },
  { ticker: "ERF.PA", expectedName: "Eurofins Scientific", indices: ["CAC 40"] },
  { ticker: "RMS.PA", expectedName: "Hermès", indices: ["CAC 40"] },
  { ticker: "KER.PA", expectedName: "Kering", indices: ["CAC 40"] },
  { ticker: "LR.PA", expectedName: "Legrand", indices: ["CAC 40"] },
  { ticker: "OR.PA", expectedName: "L'Oréal", indices: ["CAC 40"] },
  { ticker: "MC.PA", expectedName: "LVMH", indices: ["CAC 40"] },
  { ticker: "ML.PA", expectedName: "Michelin", indices: ["CAC 40"] },
  { ticker: "ORA.PA", expectedName: "Orange", indices: ["CAC 40"] },
  { ticker: "RI.PA", expectedName: "Pernod Ricard", indices: ["CAC 40"] },
  { ticker: "PUB.PA", expectedName: "Publicis", indices: ["CAC 40"] },
  { ticker: "RNO.PA", expectedName: "Renault", indices: ["CAC 40"] },
  { ticker: "SAF.PA", expectedName: "Safran", indices: ["CAC 40"] },
  { ticker: "SGO.PA", expectedName: "Saint-Gobain", indices: ["CAC 40"] },
  { ticker: "SAN.PA", expectedName: "Sanofi", indices: ["CAC 40"] },
  { ticker: "SU.PA", expectedName: "Schneider Electric", indices: ["CAC 40"] },
  { ticker: "GLE.PA", expectedName: "Société Générale", indices: ["CAC 40"] },
  { ticker: "STLAP.PA", expectedName: "Stellantis", indices: ["CAC 40"] },
  { ticker: "STMPA.PA", expectedName: "STMicroelectronics", indices: ["CAC 40"] },
  { ticker: "TEP.PA", expectedName: "Teleperformance", indices: ["CAC 40"] },
  { ticker: "HO.PA", expectedName: "Thales", indices: ["CAC 40"] },
  { ticker: "TTE.PA", expectedName: "TotalEnergies", indices: ["CAC 40"] },
  { ticker: "URW.PA", expectedName: "Unibail-Rodamco", indices: ["CAC 40"] },
  { ticker: "VIE.PA", expectedName: "Veolia", indices: ["CAC 40"] },
  { ticker: "DG.PA", expectedName: "Vinci", indices: ["CAC 40"] },
  { ticker: "VIV.PA", expectedName: "Vivendi", indices: ["CAC 40"] },
]

// ─── CAC Next 20 (20 values) ───
const CAC_NEXT20: TickerEntry[] = [
  { ticker: "AF.PA", expectedName: "Air France-KLM", indices: ["CAC Next 20"] },
  { ticker: "ATO.PA", expectedName: "Atos", indices: ["CAC Next 20"] },
  { ticker: "BIM.PA", expectedName: "bioMérieux", indices: ["CAC Next 20"] },
  { ticker: "BOL.PA", expectedName: "Bolloré", indices: ["CAC Next 20"] },
  { ticker: "AM.PA", expectedName: "Dassault Aviation", indices: ["CAC Next 20"] },
  { ticker: "EDEN.PA", expectedName: "Edenred", indices: ["CAC Next 20"] },
  { ticker: "FGR.PA", expectedName: "Eiffage", indices: ["CAC Next 20"] },
  { ticker: "ERA.PA", expectedName: "Eramet", indices: ["CAC Next 20"] },
  { ticker: "FNAC.PA", expectedName: "Fnac Darty", indices: ["CAC Next 20"] },
  { ticker: "GET.PA", expectedName: "Getlink", indices: ["CAC Next 20"] },
  { ticker: "GTT.PA", expectedName: "GTT", indices: ["CAC Next 20"] },
  { ticker: "NK.PA", expectedName: "Imerys", indices: ["CAC Next 20"] },
  { ticker: "IPS.PA", expectedName: "Ipsos", indices: ["CAC Next 20"] },
  { ticker: "RCO.PA", expectedName: "Rémy Cointreau", indices: ["CAC Next 20"] },
  { ticker: "RXL.PA", expectedName: "Rexel", indices: ["CAC Next 20"] },
  { ticker: "SK.PA", expectedName: "SEB", indices: ["CAC Next 20"] },
  { ticker: "SW.PA", expectedName: "Sodexo", indices: ["CAC Next 20"] },
  { ticker: "SOI.PA", expectedName: "Soitec", indices: ["CAC Next 20"] },
  { ticker: "WLN.PA", expectedName: "Worldline", indices: ["CAC Next 20"] },
]

// ─── CAC Mid 60 (selection of most liquid) ───
const CAC_MID60: TickerEntry[] = [
  { ticker: "AKE.PA", expectedName: "Arkema", indices: ["CAC Mid 60"] },
  { ticker: "BVI.PA", expectedName: "Bureau Veritas", indices: ["CAC Mid 60"] },
  { ticker: "CGG.PA", expectedName: "CGG", indices: ["CAC Mid 60"] },
  { ticker: "COV.PA", expectedName: "Covivio", indices: ["CAC Mid 60"] },
  { ticker: "DIM.PA", expectedName: "Sartorius Stedim", indices: ["CAC Mid 60"] },
  { ticker: "EAPI.PA", expectedName: "Euroapi", indices: ["CAC Mid 60"] },
  { ticker: "FDJ.PA", expectedName: "FDJ", indices: ["CAC Mid 60"] },
  { ticker: "FRVIA.PA", expectedName: "Forvia", indices: ["CAC Mid 60"] },
  { ticker: "FTI", expectedName: "TechnipFMC", indices: ["CAC Mid 60"] },
  { ticker: "GFC.PA", expectedName: "Gecina", indices: ["CAC Mid 60"] },
  { ticker: "GBT.PA", expectedName: "Guerbet", indices: ["CAC Mid 60"] },
  { ticker: "IDL.PA", expectedName: "ID Logistics", indices: ["CAC Mid 60"] },
  { ticker: "IPN.PA", expectedName: "Ipsen", indices: ["CAC Mid 60"] },
  { ticker: "KOF.PA", expectedName: "Kaufman & Broad", indices: ["CAC Mid 60"] },
  { ticker: "MMB.PA", expectedName: "Lagardère", indices: ["CAC Mid 60"] },
  { ticker: "LI.PA", expectedName: "Klepierre", indices: ["CAC Mid 60"] },
  { ticker: "MF.PA", expectedName: "Wendel", indices: ["CAC Mid 60"] },
  { ticker: "NEX.PA", expectedName: "Nexans", indices: ["CAC Mid 60"] },
  { ticker: "NXI.PA", expectedName: "Nexity", indices: ["CAC Mid 60"] },
  { ticker: "OPM.PA", expectedName: "OPmobility", indices: ["CAC Mid 60"] },
  { ticker: "OVH.PA", expectedName: "OVHcloud", indices: ["CAC Mid 60"] },
  { ticker: "POM.PA", expectedName: "Plastic Omnium", indices: ["CAC Mid 60"] },
  { ticker: "QDT.PA", expectedName: "Quadient", indices: ["CAC Mid 60"] },
  { ticker: "RUI.PA", expectedName: "Rubis", indices: ["CAC Mid 60"] },
  { ticker: "SCR.PA", expectedName: "Scor", indices: ["CAC Mid 60"] },
  { ticker: "SOP.PA", expectedName: "Sopra Steria", indices: ["CAC Mid 60"] },
  { ticker: "TFI.PA", expectedName: "TF1", indices: ["CAC Mid 60"] },
  { ticker: "TKO.PA", expectedName: "Tikehau Capital", indices: ["CAC Mid 60"] },
  { ticker: "UBI.PA", expectedName: "Ubisoft", indices: ["CAC Mid 60"] },
  { ticker: "VAL.PA", expectedName: "Vallourec", indices: ["CAC Mid 60"] },
  { ticker: "VIRP.PA", expectedName: "Virbac", indices: ["CAC Mid 60"] },
  { ticker: "VLA.PA", expectedName: "Valneva", indices: ["CAC Mid 60"] },
]

// ─── Germany — DAX 40 ───
const DAX40: TickerEntry[] = [
  { ticker: "ADS.DE", expectedName: "Adidas", indices: ["DAX 40"] },
  { ticker: "AIR.DE", expectedName: "Airbus (Xetra)", indices: ["DAX 40"] },
  { ticker: "ALV.DE", expectedName: "Allianz", indices: ["DAX 40"] },
  { ticker: "BAS.DE", expectedName: "BASF", indices: ["DAX 40"] },
  { ticker: "BAYN.DE", expectedName: "Bayer", indices: ["DAX 40"] },
  { ticker: "BEI.DE", expectedName: "Beiersdorf", indices: ["DAX 40"] },
  { ticker: "BMW.DE", expectedName: "BMW", indices: ["DAX 40"] },
  { ticker: "BNR.DE", expectedName: "Brenntag", indices: ["DAX 40"] },
  { ticker: "CON.DE", expectedName: "Continental", indices: ["DAX 40"] },
  { ticker: "1COV.DE", expectedName: "Covestro", indices: ["DAX 40"] },
  { ticker: "DBK.DE", expectedName: "Deutsche Bank", indices: ["DAX 40"] },
  { ticker: "DB1.DE", expectedName: "Deutsche Börse", indices: ["DAX 40"] },
  { ticker: "DHL.DE", expectedName: "DHL Group", indices: ["DAX 40"] },
  { ticker: "DTE.DE", expectedName: "Deutsche Telekom", indices: ["DAX 40"] },
  { ticker: "ENR.DE", expectedName: "Siemens Energy", indices: ["DAX 40"] },
  { ticker: "FRE.DE", expectedName: "Fresenius", indices: ["DAX 40"] },
  { ticker: "HEN3.DE", expectedName: "Henkel", indices: ["DAX 40"] },
  { ticker: "HNR1.DE", expectedName: "Hannover Rück", indices: ["DAX 40"] },
  { ticker: "IFX.DE", expectedName: "Infineon", indices: ["DAX 40"] },
  { ticker: "MBG.DE", expectedName: "Mercedes-Benz", indices: ["DAX 40"] },
  { ticker: "MRK.DE", expectedName: "Merck KGaA", indices: ["DAX 40"] },
  { ticker: "MTX.DE", expectedName: "MTU Aero Engines", indices: ["DAX 40"] },
  { ticker: "MUV2.DE", expectedName: "Munich Re", indices: ["DAX 40"] },
  { ticker: "P911.DE", expectedName: "Porsche AG", indices: ["DAX 40"] },
  { ticker: "PAH3.DE", expectedName: "Porsche Automobil", indices: ["DAX 40"] },
  { ticker: "QIA.DE", expectedName: "Qiagen", indices: ["DAX 40"] },
  { ticker: "RHM.DE", expectedName: "Rheinmetall", indices: ["DAX 40"] },
  { ticker: "RWE.DE", expectedName: "RWE", indices: ["DAX 40"] },
  { ticker: "SAP.DE", expectedName: "SAP", indices: ["DAX 40"] },
  { ticker: "SHL.DE", expectedName: "Siemens Healthineers", indices: ["DAX 40"] },
  { ticker: "SIE.DE", expectedName: "Siemens", indices: ["DAX 40"] },
  { ticker: "SY1.DE", expectedName: "Symrise", indices: ["DAX 40"] },
  { ticker: "VNA.DE", expectedName: "Vonovia", indices: ["DAX 40"] },
  { ticker: "VOW3.DE", expectedName: "Volkswagen", indices: ["DAX 40"] },
  { ticker: "ZAL.DE", expectedName: "Zalando", indices: ["DAX 40"] },
  { ticker: "DHER.DE", expectedName: "Delivery Hero", indices: ["DAX 40"] },
  { ticker: "LEG.DE", expectedName: "LEG Immobilien", indices: ["DAX 40"] },
]

// ─── Netherlands — AEX 25 ───
const AEX25: TickerEntry[] = [
  { ticker: "ADYEN.AS", expectedName: "Adyen", indices: ["AEX 25"] },
  { ticker: "AGN.AS", expectedName: "Aegon", indices: ["AEX 25"] },
  { ticker: "AKZA.AS", expectedName: "Akzo Nobel", indices: ["AEX 25"] },
  { ticker: "ASM.AS", expectedName: "ASM International", indices: ["AEX 25"] },
  { ticker: "ASML.AS", expectedName: "ASML", indices: ["AEX 25"] },
  { ticker: "BESI.AS", expectedName: "BE Semiconductor", indices: ["AEX 25"] },
  { ticker: "HEIA.AS", expectedName: "Heineken", indices: ["AEX 25"] },
  { ticker: "INGA.AS", expectedName: "ING Groep", indices: ["AEX 25"] },
  { ticker: "KPN.AS", expectedName: "KPN", indices: ["AEX 25"] },
  { ticker: "NN.AS", expectedName: "NN Group", indices: ["AEX 25"] },
  { ticker: "PHIA.AS", expectedName: "Philips", indices: ["AEX 25"] },
  { ticker: "PRX.AS", expectedName: "Prosus", indices: ["AEX 25"] },
  { ticker: "RAND.AS", expectedName: "Randstad", indices: ["AEX 25"] },
  { ticker: "UNA.AS", expectedName: "Unilever", indices: ["AEX 25"] },
  { ticker: "WKL.AS", expectedName: "Wolters Kluwer", indices: ["AEX 25"] },
  { ticker: "IMCD.AS", expectedName: "IMCD", indices: ["AEX 25"] },
  { ticker: "SHELL.AS", expectedName: "Shell", indices: ["AEX 25"] },
  { ticker: "ABN.AS", expectedName: "ABN AMRO", indices: ["AEX 25"] },
  { ticker: "AH.AS", expectedName: "Ahold Delhaize", indices: ["AEX 25"] },
  { ticker: "DSFIR.AS", expectedName: "DSM-Firmenich", indices: ["AEX 25"] },
  { ticker: "EXO.AS", expectedName: "Exor", indices: ["AEX 25"] },
  { ticker: "UMG.AS", expectedName: "Universal Music", indices: ["AEX 25"] },
]

// ─── Belgium — BEL 20 ───
const BEL20: TickerEntry[] = [
  { ticker: "ABI.BR", expectedName: "AB InBev", indices: ["BEL 20"] },
  { ticker: "ARGX.BR", expectedName: "argenx", indices: ["BEL 20"] },
  { ticker: "GBLB.BR", expectedName: "GBL", indices: ["BEL 20"] },
  { ticker: "KBC.BR", expectedName: "KBC Group", indices: ["BEL 20"] },
  { ticker: "SOLB.BR", expectedName: "Solvay", indices: ["BEL 20"] },
  { ticker: "UCB.BR", expectedName: "UCB", indices: ["BEL 20"] },
  { ticker: "UMI.BR", expectedName: "Umicore", indices: ["BEL 20"] },
  { ticker: "COFB.BR", expectedName: "Cofinimmo", indices: ["BEL 20"] },
  { ticker: "ACKB.BR", expectedName: "Ackermans & vH", indices: ["BEL 20"] },
  { ticker: "AGS.BR", expectedName: "ageas", indices: ["BEL 20"] },
  { ticker: "PROX.BR", expectedName: "Proximus", indices: ["BEL 20"] },
  { ticker: "WDP.BR", expectedName: "WDP", indices: ["BEL 20"] },
]

// ─── Spain — IBEX 35 (selection) ───
const IBEX: TickerEntry[] = [
  { ticker: "SAN.MC", expectedName: "Banco Santander", indices: ["IBEX 35"] },
  { ticker: "BBVA.MC", expectedName: "BBVA", indices: ["IBEX 35"] },
  { ticker: "ITX.MC", expectedName: "Inditex", indices: ["IBEX 35"] },
  { ticker: "IBE.MC", expectedName: "Iberdrola", indices: ["IBEX 35"] },
  { ticker: "TEF.MC", expectedName: "Telefónica", indices: ["IBEX 35"] },
  { ticker: "REP.MC", expectedName: "Repsol", indices: ["IBEX 35"] },
  { ticker: "AMS.MC", expectedName: "Amadeus IT", indices: ["IBEX 35"] },
  { ticker: "FER.MC", expectedName: "Ferrovial", indices: ["IBEX 35"] },
  { ticker: "CABK.MC", expectedName: "CaixaBank", indices: ["IBEX 35"] },
  { ticker: "ENG.MC", expectedName: "Enagás", indices: ["IBEX 35"] },
  { ticker: "RED.MC", expectedName: "Red Eléctrica", indices: ["IBEX 35"] },
  { ticker: "ACS.MC", expectedName: "ACS", indices: ["IBEX 35"] },
  { ticker: "CLNX.MC", expectedName: "Cellnex", indices: ["IBEX 35"] },
  { ticker: "GRF.MC", expectedName: "Grifols", indices: ["IBEX 35"] },
  { ticker: "MAP.MC", expectedName: "Mapfre", indices: ["IBEX 35"] },
]

// ─── Italy (selection) ───
const ITALY: TickerEntry[] = [
  { ticker: "ENI.MI", expectedName: "Eni", indices: [] },
  { ticker: "ISP.MI", expectedName: "Intesa Sanpaolo", indices: [] },
  { ticker: "ENEL.MI", expectedName: "Enel", indices: [] },
  { ticker: "UCG.MI", expectedName: "UniCredit", indices: [] },
  { ticker: "G.MI", expectedName: "Generali", indices: [] },
  { ticker: "RACE.MI", expectedName: "Ferrari", indices: [] },
  { ticker: "LDO.MI", expectedName: "Leonardo", indices: [] },
  { ticker: "TIT.MI", expectedName: "Telecom Italia", indices: [] },
  { ticker: "BAMI.MI", expectedName: "Banco BPM", indices: [] },
  { ticker: "CPR.MI", expectedName: "Campari", indices: [] },
  { ticker: "TEN.MI", expectedName: "Tenaris", indices: [] },
  { ticker: "SRG.MI", expectedName: "Snam", indices: [] },
  { ticker: "PRY.MI", expectedName: "Prysmian", indices: [] },
  { ticker: "PST.MI", expectedName: "Poste Italiane", indices: [] },
  { ticker: "STMMI.MI", expectedName: "STMicro (Milan)", indices: [] },
]

// ─── Portugal ───
const PORTUGAL: TickerEntry[] = [
  { ticker: "EDP.LS", expectedName: "EDP", indices: [] },
  { ticker: "GALP.LS", expectedName: "Galp Energia", indices: [] },
  { ticker: "JMT.LS", expectedName: "Jerónimo Martins", indices: [] },
  { ticker: "SON.LS", expectedName: "Sonae", indices: [] },
]

// ─── Finland ───
const FINLAND: TickerEntry[] = [
  { ticker: "NOKIA.HE", expectedName: "Nokia", indices: [] },
  { ticker: "SAMPO.HE", expectedName: "Sampo", indices: [] },
  { ticker: "FORTUM.HE", expectedName: "Fortum", indices: [] },
  { ticker: "UPM.HE", expectedName: "UPM-Kymmene", indices: [] },
  { ticker: "STERV.HE", expectedName: "Stora Enso", indices: [] },
  { ticker: "NESTE.HE", expectedName: "Neste", indices: [] },
  { ticker: "WRT1V.HE", expectedName: "Wärtsilä", indices: [] },
  { ticker: "KNEBV.HE", expectedName: "Kone", indices: [] },
  { ticker: "ELISA.HE", expectedName: "Elisa", indices: [] },
]

// ─── Ireland ───
const IRELAND: TickerEntry[] = [
  { ticker: "CRH.L", expectedName: "CRH", indices: [] },
  { ticker: "SKG.L", expectedName: "Smurfit Kappa", indices: [] },
  { ticker: "KYGA.L", expectedName: "Kerry Group", indices: [] },
  { ticker: "BIRG.L", expectedName: "Bank of Ireland", indices: [] },
]

// ─── Austria ───
const AUSTRIA: TickerEntry[] = [
  { ticker: "VOE.VI", expectedName: "Voestalpine", indices: [] },
  { ticker: "OMV.VI", expectedName: "OMV", indices: [] },
  { ticker: "EBS.VI", expectedName: "Erste Group", indices: [] },
  { ticker: "VER.VI", expectedName: "Verbund", indices: [] },
  { ticker: "WIE.VI", expectedName: "Wienerberger", indices: [] },
]

// ─── USA — S&P 500 Top 100 ───
const SP500: TickerEntry[] = [
  { ticker: "AAPL", expectedName: "Apple", indices: ["S&P 500"] },
  { ticker: "MSFT", expectedName: "Microsoft", indices: ["S&P 500"] },
  { ticker: "NVDA", expectedName: "NVIDIA", indices: ["S&P 500"] },
  { ticker: "AMZN", expectedName: "Amazon", indices: ["S&P 500"] },
  { ticker: "META", expectedName: "Meta Platforms", indices: ["S&P 500"] },
  { ticker: "GOOGL", expectedName: "Alphabet (Class A)", indices: ["S&P 500"] },
  { ticker: "GOOG", expectedName: "Alphabet (Class C)", indices: ["S&P 500"] },
  { ticker: "BRK-B", expectedName: "Berkshire Hathaway", indices: ["S&P 500"] },
  { ticker: "TSLA", expectedName: "Tesla", indices: ["S&P 500"] },
  { ticker: "LLY", expectedName: "Eli Lilly", indices: ["S&P 500"] },
  { ticker: "AVGO", expectedName: "Broadcom", indices: ["S&P 500"] },
  { ticker: "V", expectedName: "Visa", indices: ["S&P 500"] },
  { ticker: "JPM", expectedName: "JPMorgan Chase", indices: ["S&P 500"] },
  { ticker: "UNH", expectedName: "UnitedHealth Group", indices: ["S&P 500"] },
  { ticker: "WMT", expectedName: "Walmart", indices: ["S&P 500"] },
  { ticker: "MA", expectedName: "Mastercard", indices: ["S&P 500"] },
  { ticker: "XOM", expectedName: "Exxon Mobil", indices: ["S&P 500"] },
  { ticker: "JNJ", expectedName: "Johnson & Johnson", indices: ["S&P 500"] },
  { ticker: "PG", expectedName: "Procter & Gamble", indices: ["S&P 500"] },
  { ticker: "HD", expectedName: "Home Depot", indices: ["S&P 500"] },
  { ticker: "COST", expectedName: "Costco Wholesale", indices: ["S&P 500"] },
  { ticker: "MRK", expectedName: "Merck & Co.", indices: ["S&P 500"] },
  { ticker: "ABBV", expectedName: "AbbVie", indices: ["S&P 500"] },
  { ticker: "CRM", expectedName: "Salesforce", indices: ["S&P 500"] },
  { ticker: "CVX", expectedName: "Chevron", indices: ["S&P 500"] },
  { ticker: "AMD", expectedName: "Advanced Micro Devices", indices: ["S&P 500"] },
  { ticker: "NFLX", expectedName: "Netflix", indices: ["S&P 500"] },
  { ticker: "PEP", expectedName: "PepsiCo", indices: ["S&P 500"] },
  { ticker: "KO", expectedName: "Coca-Cola", indices: ["S&P 500"] },
  { ticker: "BAC", expectedName: "Bank of America", indices: ["S&P 500"] },
  { ticker: "ADBE", expectedName: "Adobe", indices: ["S&P 500"] },
  { ticker: "LIN", expectedName: "Linde", indices: ["S&P 500"] },
  { ticker: "TMO", expectedName: "Thermo Fisher Scientific", indices: ["S&P 500"] },
  { ticker: "MCD", expectedName: "McDonald's", indices: ["S&P 500"] },
  { ticker: "CSCO", expectedName: "Cisco Systems", indices: ["S&P 500"] },
  { ticker: "INTU", expectedName: "Intuit", indices: ["S&P 500"] },
  { ticker: "ABT", expectedName: "Abbott Laboratories", indices: ["S&P 500"] },
  { ticker: "QCOM", expectedName: "Qualcomm", indices: ["S&P 500"] },
  { ticker: "WFC", expectedName: "Wells Fargo", indices: ["S&P 500"] },
  { ticker: "DHR", expectedName: "Danaher", indices: ["S&P 500"] },
  { ticker: "GE", expectedName: "General Electric", indices: ["S&P 500"] },
  { ticker: "IBM", expectedName: "IBM", indices: ["S&P 500"] },
  { ticker: "AXP", expectedName: "American Express", indices: ["S&P 500"] },
  { ticker: "CAT", expectedName: "Caterpillar", indices: ["S&P 500"] },
  { ticker: "VZ", expectedName: "Verizon", indices: ["S&P 500"] },
  { ticker: "TXN", expectedName: "Texas Instruments", indices: ["S&P 500"] },
  { ticker: "DIS", expectedName: "Walt Disney", indices: ["S&P 500"] },
  { ticker: "AMGN", expectedName: "Amgen", indices: ["S&P 500"] },
  { ticker: "PFE", expectedName: "Pfizer", indices: ["S&P 500"] },
  { ticker: "NOW", expectedName: "ServiceNow", indices: ["S&P 500"] },
  // 51–100
  { ticker: "ORCL", expectedName: "Oracle", indices: ["S&P 500"] },
  { ticker: "GS", expectedName: "Goldman Sachs", indices: ["S&P 500"] },
  { ticker: "MS", expectedName: "Morgan Stanley", indices: ["S&P 500"] },
  { ticker: "RTX", expectedName: "RTX Corporation", indices: ["S&P 500"] },
  { ticker: "ISRG", expectedName: "Intuitive Surgical", indices: ["S&P 500"] },
  { ticker: "BKNG", expectedName: "Booking Holdings", indices: ["S&P 500"] },
  { ticker: "BLK", expectedName: "BlackRock", indices: ["S&P 500"] },
  { ticker: "SPGI", expectedName: "S&P Global", indices: ["S&P 500"] },
  { ticker: "T", expectedName: "AT&T", indices: ["S&P 500"] },
  { ticker: "C", expectedName: "Citigroup", indices: ["S&P 500"] },
  { ticker: "SCHW", expectedName: "Charles Schwab", indices: ["S&P 500"] },
  { ticker: "ADP", expectedName: "Automatic Data Processing", indices: ["S&P 500"] },
  { ticker: "TMUS", expectedName: "T-Mobile US", indices: ["S&P 500"] },
  { ticker: "BMY", expectedName: "Bristol-Myers Squibb", indices: ["S&P 500"] },
  { ticker: "SYK", expectedName: "Stryker", indices: ["S&P 500"] },
  { ticker: "DE", expectedName: "Deere & Company", indices: ["S&P 500"] },
  { ticker: "MU", expectedName: "Micron Technology", indices: ["S&P 500"] },
  { ticker: "PANW", expectedName: "Palo Alto Networks", indices: ["S&P 500"] },
  { ticker: "COP", expectedName: "ConocoPhillips", indices: ["S&P 500"] },
  { ticker: "SBUX", expectedName: "Starbucks", indices: ["S&P 500"] },
  { ticker: "CI", expectedName: "Cigna Group", indices: ["S&P 500"] },
  { ticker: "ELV", expectedName: "Elevance Health", indices: ["S&P 500"] },
  { ticker: "GILD", expectedName: "Gilead Sciences", indices: ["S&P 500"] },
  { ticker: "AMT", expectedName: "American Tower", indices: ["S&P 500"] },
  { ticker: "TJX", expectedName: "TJX Companies", indices: ["S&P 500"] },
  { ticker: "USB", expectedName: "U.S. Bancorp", indices: ["S&P 500"] },
  { ticker: "PNC", expectedName: "PNC Financial Services", indices: ["S&P 500"] },
  { ticker: "ETN", expectedName: "Eaton Corporation", indices: ["S&P 500"] },
  { ticker: "LMT", expectedName: "Lockheed Martin", indices: ["S&P 500"] },
  { ticker: "NOC", expectedName: "Northrop Grumman", indices: ["S&P 500"] },
  { ticker: "DUK", expectedName: "Duke Energy", indices: ["S&P 500"] },
  { ticker: "BA", expectedName: "Boeing", indices: ["S&P 500"] },
  { ticker: "INTC", expectedName: "Intel", indices: ["S&P 500"] },
  { ticker: "ICE", expectedName: "Intercontinental Exchange", indices: ["S&P 500"] },
  { ticker: "CME", expectedName: "CME Group", indices: ["S&P 500"] },
  { ticker: "PLD", expectedName: "Prologis", indices: ["S&P 500"] },
  { ticker: "MDLZ", expectedName: "Mondelez International", indices: ["S&P 500"] },
  { ticker: "ZTS", expectedName: "Zoetis", indices: ["S&P 500"] },
  { ticker: "SHW", expectedName: "Sherwin-Williams", indices: ["S&P 500"] },
  { ticker: "SO", expectedName: "Southern Company", indices: ["S&P 500"] },
  { ticker: "EOG", expectedName: "EOG Resources", indices: ["S&P 500"] },
  { ticker: "MO", expectedName: "Altria Group", indices: ["S&P 500"] },
  { ticker: "APH", expectedName: "Amphenol", indices: ["S&P 500"] },
  { ticker: "EMR", expectedName: "Emerson Electric", indices: ["S&P 500"] },
  { ticker: "CL", expectedName: "Colgate-Palmolive", indices: ["S&P 500"] },
  { ticker: "GM", expectedName: "General Motors", indices: ["S&P 500"] },
  { ticker: "F", expectedName: "Ford Motor", indices: ["S&P 500"] },
  { ticker: "TGT", expectedName: "Target", indices: ["S&P 500"] },
  { ticker: "MMM", expectedName: "3M", indices: ["S&P 500"] },
  { ticker: "CB", expectedName: "Chubb", indices: ["S&P 500"] },
]

// ─── China — Top 100 (Hong Kong + ADRs US) ───
const CHINA_TOP100: TickerEntry[] = [
  // HK-listed
  { ticker: "0700.HK", expectedName: "Tencent", indices: ["Chine Top 100"] },
  { ticker: "0941.HK", expectedName: "China Mobile", indices: ["Chine Top 100"] },
  { ticker: "1398.HK", expectedName: "ICBC", indices: ["Chine Top 100"] },
  { ticker: "0939.HK", expectedName: "CCB", indices: ["Chine Top 100"] },
  { ticker: "3988.HK", expectedName: "Bank of China", indices: ["Chine Top 100"] },
  { ticker: "2318.HK", expectedName: "Ping An Insurance", indices: ["Chine Top 100"] },
  { ticker: "0883.HK", expectedName: "CNOOC", indices: ["Chine Top 100"] },
  { ticker: "0386.HK", expectedName: "Sinopec", indices: ["Chine Top 100"] },
  { ticker: "0857.HK", expectedName: "PetroChina", indices: ["Chine Top 100"] },
  { ticker: "1810.HK", expectedName: "Xiaomi", indices: ["Chine Top 100"] },
  { ticker: "3690.HK", expectedName: "Meituan", indices: ["Chine Top 100"] },
  { ticker: "9988.HK", expectedName: "Alibaba (HK)", indices: ["Chine Top 100"] },
  { ticker: "9618.HK", expectedName: "JD.com (HK)", indices: ["Chine Top 100"] },
  { ticker: "9888.HK", expectedName: "Baidu (HK)", indices: ["Chine Top 100"] },
  { ticker: "9999.HK", expectedName: "NetEase (HK)", indices: ["Chine Top 100"] },
  { ticker: "9961.HK", expectedName: "Trip.com (HK)", indices: ["Chine Top 100"] },
  { ticker: "0175.HK", expectedName: "Geely Automobile", indices: ["Chine Top 100"] },
  { ticker: "1024.HK", expectedName: "Kuaishou", indices: ["Chine Top 100"] },
  { ticker: "0388.HK", expectedName: "HKEX", indices: ["Chine Top 100"] },
  { ticker: "2020.HK", expectedName: "ANTA Sports", indices: ["Chine Top 100"] },
  { ticker: "1211.HK", expectedName: "BYD (HK)", indices: ["Chine Top 100"] },
  { ticker: "2269.HK", expectedName: "Wuxi Biologics", indices: ["Chine Top 100"] },
  { ticker: "0762.HK", expectedName: "China Unicom", indices: ["Chine Top 100"] },
  { ticker: "0728.HK", expectedName: "China Telecom (HK)", indices: ["Chine Top 100"] },
  { ticker: "2313.HK", expectedName: "Shenzhou International", indices: ["Chine Top 100"] },
  { ticker: "0669.HK", expectedName: "Techtronic Industries", indices: ["Chine Top 100"] },
  { ticker: "2382.HK", expectedName: "Sunny Optical", indices: ["Chine Top 100"] },
  { ticker: "6690.HK", expectedName: "Haier Smart Home (HK)", indices: ["Chine Top 100"] },
  { ticker: "9868.HK", expectedName: "XPeng (HK)", indices: ["Chine Top 100"] },
  { ticker: "2015.HK", expectedName: "Li Auto (HK)", indices: ["Chine Top 100"] },
  { ticker: "6862.HK", expectedName: "Haidilao", indices: ["Chine Top 100"] },
  { ticker: "9901.HK", expectedName: "New Oriental (HK)", indices: ["Chine Top 100"] },
  { ticker: "0066.HK", expectedName: "MTR Corporation", indices: ["Chine Top 100"] },
  { ticker: "1093.HK", expectedName: "CSPC Pharma", indices: ["Chine Top 100"] },
  { ticker: "3968.HK", expectedName: "China Merchants Bank", indices: ["Chine Top 100"] },
  { ticker: "2628.HK", expectedName: "China Life Insurance", indices: ["Chine Top 100"] },
  { ticker: "6098.HK", expectedName: "Country Garden Services", indices: ["Chine Top 100"] },
  { ticker: "0002.HK", expectedName: "CLP Holdings", indices: ["Chine Top 100"] },
  { ticker: "0012.HK", expectedName: "Henderson Land", indices: ["Chine Top 100"] },
  { ticker: "0016.HK", expectedName: "Sun Hung Kai Properties", indices: ["Chine Top 100"] },
  { ticker: "1177.HK", expectedName: "Sino Biopharmaceutical", indices: ["Chine Top 100"] },
  { ticker: "0688.HK", expectedName: "China Overseas Land", indices: ["Chine Top 100"] },
  { ticker: "9698.HK", expectedName: "GDS Holdings (HK)", indices: ["Chine Top 100"] },
  { ticker: "0960.HK", expectedName: "Longfor Properties", indices: ["Chine Top 100"] },
  { ticker: "1997.HK", expectedName: "Wharf REIC", indices: ["Chine Top 100"] },
  { ticker: "0011.HK", expectedName: "Hang Seng Bank", indices: ["Chine Top 100"] },
  // US ADRs
  { ticker: "BABA", expectedName: "Alibaba Group", indices: ["Chine Top 100"] },
  { ticker: "PDD", expectedName: "PDD Holdings", indices: ["Chine Top 100"] },
  { ticker: "JD", expectedName: "JD.com", indices: ["Chine Top 100"] },
  { ticker: "BIDU", expectedName: "Baidu", indices: ["Chine Top 100"] },
  { ticker: "NTES", expectedName: "NetEase", indices: ["Chine Top 100"] },
  { ticker: "NIO", expectedName: "NIO", indices: ["Chine Top 100"] },
  { ticker: "XPEV", expectedName: "XPeng", indices: ["Chine Top 100"] },
  { ticker: "LI", expectedName: "Li Auto", indices: ["Chine Top 100"] },
  { ticker: "TME", expectedName: "Tencent Music", indices: ["Chine Top 100"] },
  { ticker: "YUMC", expectedName: "Yum China", indices: ["Chine Top 100"] },
  { ticker: "VIPS", expectedName: "Vipshop", indices: ["Chine Top 100"] },
  { ticker: "IQ", expectedName: "iQIYI", indices: ["Chine Top 100"] },
  { ticker: "FUTU", expectedName: "Futu Holdings", indices: ["Chine Top 100"] },
  { ticker: "TAL", expectedName: "TAL Education", indices: ["Chine Top 100"] },
]

// ─── Japan — Nikkei / TSE Top 80 ───
const JAPAN_TOP80: TickerEntry[] = [
  { ticker: "7203.T", expectedName: "Toyota Motor", indices: ["Japon Top 100"] },
  { ticker: "9432.T", expectedName: "NTT", indices: ["Japon Top 100"] },
  { ticker: "8306.T", expectedName: "Mitsubishi UFJ Financial", indices: ["Japon Top 100"] },
  { ticker: "6758.T", expectedName: "Sony Group", indices: ["Japon Top 100"] },
  { ticker: "9984.T", expectedName: "SoftBank Group", indices: ["Japon Top 100"] },
  { ticker: "6861.T", expectedName: "Keyence", indices: ["Japon Top 100"] },
  { ticker: "7974.T", expectedName: "Nintendo", indices: ["Japon Top 100"] },
  { ticker: "8035.T", expectedName: "Tokyo Electron", indices: ["Japon Top 100"] },
  { ticker: "9433.T", expectedName: "KDDI", indices: ["Japon Top 100"] },
  { ticker: "7267.T", expectedName: "Honda Motor", indices: ["Japon Top 100"] },
  { ticker: "4502.T", expectedName: "Takeda Pharmaceutical", indices: ["Japon Top 100"] },
  { ticker: "6501.T", expectedName: "Hitachi", indices: ["Japon Top 100"] },
  { ticker: "6954.T", expectedName: "Fanuc", indices: ["Japon Top 100"] },
  { ticker: "4063.T", expectedName: "Shin-Etsu Chemical", indices: ["Japon Top 100"] },
  { ticker: "6367.T", expectedName: "Daikin Industries", indices: ["Japon Top 100"] },
  { ticker: "8316.T", expectedName: "Sumitomo Mitsui Financial", indices: ["Japon Top 100"] },
  { ticker: "4661.T", expectedName: "Oriental Land", indices: ["Japon Top 100"] },
  { ticker: "7741.T", expectedName: "HOYA", indices: ["Japon Top 100"] },
  { ticker: "6981.T", expectedName: "Murata Manufacturing", indices: ["Japon Top 100"] },
  { ticker: "4519.T", expectedName: "Chugai Pharmaceutical", indices: ["Japon Top 100"] },
  { ticker: "2914.T", expectedName: "Japan Tobacco", indices: ["Japon Top 100"] },
  { ticker: "4568.T", expectedName: "Daiichi Sankyo", indices: ["Japon Top 100"] },
  { ticker: "9022.T", expectedName: "Central Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "8411.T", expectedName: "Mizuho Financial Group", indices: ["Japon Top 100"] },
  { ticker: "7751.T", expectedName: "Canon", indices: ["Japon Top 100"] },
  { ticker: "9434.T", expectedName: "SoftBank Corp", indices: ["Japon Top 100"] },
  { ticker: "6702.T", expectedName: "Fujitsu", indices: ["Japon Top 100"] },
  { ticker: "6503.T", expectedName: "Mitsubishi Electric", indices: ["Japon Top 100"] },
  { ticker: "4523.T", expectedName: "Eisai", indices: ["Japon Top 100"] },
  { ticker: "8058.T", expectedName: "Mitsubishi Corporation", indices: ["Japon Top 100"] },
  { ticker: "8031.T", expectedName: "Mitsui & Co", indices: ["Japon Top 100"] },
  { ticker: "9020.T", expectedName: "East Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "8801.T", expectedName: "Mitsui Fudosan", indices: ["Japon Top 100"] },
  { ticker: "5401.T", expectedName: "Nippon Steel", indices: ["Japon Top 100"] },
  { ticker: "9983.T", expectedName: "Fast Retailing", indices: ["Japon Top 100"] },
  { ticker: "4911.T", expectedName: "Shiseido", indices: ["Japon Top 100"] },
  { ticker: "2802.T", expectedName: "Ajinomoto", indices: ["Japon Top 100"] },
  { ticker: "7733.T", expectedName: "Olympus", indices: ["Japon Top 100"] },
  { ticker: "6752.T", expectedName: "Panasonic Holdings", indices: ["Japon Top 100"] },
  { ticker: "3382.T", expectedName: "Seven & I Holdings", indices: ["Japon Top 100"] },
  { ticker: "4452.T", expectedName: "Kao", indices: ["Japon Top 100"] },
  { ticker: "2503.T", expectedName: "Kirin Holdings", indices: ["Japon Top 100"] },
  { ticker: "9101.T", expectedName: "Nippon Yusen", indices: ["Japon Top 100"] },
  { ticker: "9104.T", expectedName: "Mitsui OSK Lines", indices: ["Japon Top 100"] },
  { ticker: "7011.T", expectedName: "Mitsubishi Heavy Industries", indices: ["Japon Top 100"] },
  { ticker: "4901.T", expectedName: "Fujifilm Holdings", indices: ["Japon Top 100"] },
  { ticker: "7201.T", expectedName: "Nissan Motor", indices: ["Japon Top 100"] },
  { ticker: "8002.T", expectedName: "Marubeni", indices: ["Japon Top 100"] },
  { ticker: "8053.T", expectedName: "Sumitomo Corporation", indices: ["Japon Top 100"] },
  { ticker: "6857.T", expectedName: "Advantest", indices: ["Japon Top 100"] },
  { ticker: "6723.T", expectedName: "Renesas Electronics", indices: ["Japon Top 100"] },
  { ticker: "6762.T", expectedName: "TDK", indices: ["Japon Top 100"] },
  { ticker: "5108.T", expectedName: "Bridgestone", indices: ["Japon Top 100"] },
  { ticker: "4543.T", expectedName: "Terumo", indices: ["Japon Top 100"] },
  { ticker: "4578.T", expectedName: "Otsuka Holdings", indices: ["Japon Top 100"] },
  { ticker: "8766.T", expectedName: "Tokio Marine Holdings", indices: ["Japon Top 100"] },
  { ticker: "8309.T", expectedName: "Sumitomo Mitsui Trust", indices: ["Japon Top 100"] },
  { ticker: "6971.T", expectedName: "Kyocera", indices: ["Japon Top 100"] },
  { ticker: "4062.T", expectedName: "Ibiden", indices: ["Japon Top 100"] },
  { ticker: "9021.T", expectedName: "West Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "6902.T", expectedName: "Denso", indices: ["Japon Top 100"] },
  { ticker: "3407.T", expectedName: "Asahi Kasei", indices: ["Japon Top 100"] },
  { ticker: "9107.T", expectedName: "Kawasaki Kisen Kaisha", indices: ["Japon Top 100"] },
  { ticker: "4507.T", expectedName: "Shionogi", indices: ["Japon Top 100"] },
  { ticker: "7735.T", expectedName: "Screen Holdings", indices: ["Japon Top 100"] },
  { ticker: "8028.T", expectedName: "FamilyMart (FJ)", indices: ["Japon Top 100"] },
  { ticker: "2267.T", expectedName: "Yakult Honsha", indices: ["Japon Top 100"] },
  { ticker: "2501.T", expectedName: "Sapporo Holdings", indices: ["Japon Top 100"] },
  { ticker: "4151.T", expectedName: "Kyowa Kirin", indices: ["Japon Top 100"] },
  { ticker: "3659.T", expectedName: "Nexon", indices: ["Japon Top 100"] },
  { ticker: "9613.T", expectedName: "NTT Data Group", indices: ["Japon Top 100"] },
  { ticker: "6724.T", expectedName: "Seiko Epson", indices: ["Japon Top 100"] },
  { ticker: "5803.T", expectedName: "Furukawa Electric", indices: ["Japon Top 100"] },
  { ticker: "4183.T", expectedName: "Mitsui Chemicals", indices: ["Japon Top 100"] },
  { ticker: "7261.T", expectedName: "Mazda Motor", indices: ["Japon Top 100"] },
  { ticker: "2282.T", expectedName: "NH Foods", indices: ["Japon Top 100"] },
  { ticker: "4004.T", expectedName: "Resonac Holdings", indices: ["Japon Top 100"] },
  { ticker: "8308.T", expectedName: "Resona Holdings", indices: ["Japon Top 100"] },
]

// ─── Merge & deduplicate ───

function buildUniverse(): TickerEntry[] {
  const all = [
    ...CAC40, ...CAC_NEXT20, ...CAC_MID60,
    ...DAX40, ...AEX25, ...BEL20, ...IBEX,
    ...ITALY, ...PORTUGAL, ...FINLAND, ...IRELAND, ...AUSTRIA,
    ...SP500,
    ...CHINA_TOP100,
    ...JAPAN_TOP80,
  ]

  const map = new Map<string, TickerEntry>()
  for (const entry of all) {
    const existing = map.get(entry.ticker)
    if (existing) {
      const merged = new Set([...existing.indices, ...entry.indices])
      existing.indices = Array.from(merged)
    } else {
      map.set(entry.ticker, { ...entry, indices: [...entry.indices] })
    }
  }

  // Tag SBF 120 = CAC 40 + Next 20 + Mid 60
  for (const entry of map.values()) {
    if (
      entry.indices.includes("CAC 40") ||
      entry.indices.includes("CAC Next 20") ||
      entry.indices.includes("CAC Mid 60")
    ) {
      if (!entry.indices.includes("SBF 120")) {
        entry.indices.push("SBF 120")
      }
    }
  }

  return Array.from(map.values())
}

export const UNIVERSE = buildUniverse()

export const ALL_INDICES = [
  "CAC 40",
  "CAC Next 20",
  "CAC Mid 60",
  "SBF 120",
  "DAX 40",
  "AEX 25",
  "BEL 20",
  "IBEX 35",
  "S&P 500",
  "Chine Top 100",
  "Japon Top 100",
] as const

export type IndexName = (typeof ALL_INDICES)[number]
