export interface TickerEntry {
  ticker: string
  expectedName: string
  indices: string[]
}

// ─── CAC 40 (40 values) ───
const CAC40: TickerEntry[] = [
  { ticker: "AC.PA", expectedName: "Accor", indices: ["CAC 40"] },
  { ticker: "AI.PA", expectedName: "Air Liquide", indices: ["CAC 40"] },
  { ticker: "AIR.PA", expectedName: "Airbus", indices: ["CAC 40"] },
  { ticker: "ALO.PA", expectedName: "Alstom", indices: ["CAC 40"] },
  { ticker: "MT.PA", expectedName: "ArcelorMittal", indices: ["CAC 40"] },
  { ticker: "CS.PA", expectedName: "AXA", indices: ["CAC 40"] },
  { ticker: "BNP.PA", expectedName: "BNP Paribas", indices: ["CAC 40"] },
  { ticker: "EN.PA", expectedName: "Bouygues", indices: ["CAC 40"] },
  { ticker: "CAP.PA", expectedName: "Capgemini", indices: ["CAC 40"] },
  { ticker: "CA.PA", expectedName: "Carrefour", indices: ["CAC 40"] },
  { ticker: "ACA.PA", expectedName: "Crédit Agricole", indices: ["CAC 40"] },
  { ticker: "BN.PA", expectedName: "Danone", indices: ["CAC 40"] },
  { ticker: "DSY.PA", expectedName: "Dassault Systèmes", indices: ["CAC 40"] },
  { ticker: "ENGI.PA", expectedName: "Engie", indices: ["CAC 40"] },
  { ticker: "EL.PA", expectedName: "EssilorLuxottica", indices: ["CAC 40"] },
  { ticker: "ERF.PA", expectedName: "Eurofins Scientific", indices: ["CAC 40"] },
  { ticker: "RMS.PA", expectedName: "Hermès", indices: ["CAC 40"] },
  { ticker: "KER.PA", expectedName: "Kering", indices: ["CAC 40"] },
  { ticker: "LR.PA", expectedName: "Legrand", indices: ["CAC 40"] },
  { ticker: "OR.PA", expectedName: "L'Oréal", indices: ["CAC 40"] },
  { ticker: "MC.PA", expectedName: "LVMH", indices: ["CAC 40"] },
  { ticker: "ML.PA", expectedName: "Michelin", indices: ["CAC 40"] },
  { ticker: "ORA.PA", expectedName: "Orange", indices: ["CAC 40"] },
  { ticker: "RI.PA", expectedName: "Pernod Ricard", indices: ["CAC 40"] },
  { ticker: "PUB.PA", expectedName: "Publicis", indices: ["CAC 40"] },
  { ticker: "RNO.PA", expectedName: "Renault", indices: ["CAC 40"] },
  { ticker: "SAF.PA", expectedName: "Safran", indices: ["CAC 40"] },
  { ticker: "SGO.PA", expectedName: "Saint-Gobain", indices: ["CAC 40"] },
  { ticker: "SAN.PA", expectedName: "Sanofi", indices: ["CAC 40"] },
  { ticker: "SU.PA", expectedName: "Schneider Electric", indices: ["CAC 40"] },
  { ticker: "GLE.PA", expectedName: "Société Générale", indices: ["CAC 40"] },
  { ticker: "STLAP.PA", expectedName: "Stellantis", indices: ["CAC 40"] },
  { ticker: "STMPA.PA", expectedName: "STMicroelectronics", indices: ["CAC 40"] },
  { ticker: "TEP.PA", expectedName: "Teleperformance", indices: ["CAC 40"] },
  { ticker: "HO.PA", expectedName: "Thales", indices: ["CAC 40"] },
  { ticker: "TTE.PA", expectedName: "TotalEnergies", indices: ["CAC 40"] },
  { ticker: "URW.PA", expectedName: "Unibail-Rodamco", indices: ["CAC 40"] },
  { ticker: "VIE.PA", expectedName: "Veolia", indices: ["CAC 40"] },
  { ticker: "DG.PA", expectedName: "Vinci", indices: ["CAC 40"] },
  { ticker: "VIV.PA", expectedName: "Vivendi", indices: ["CAC 40"] },
]

// ─── CAC Next 20 (20 values) ───
const CAC_NEXT20: TickerEntry[] = [
  { ticker: "AF.PA", expectedName: "Air France-KLM", indices: ["CAC Next 20"] },
  { ticker: "ATO.PA", expectedName: "Atos", indices: ["CAC Next 20"] },
  { ticker: "BIM.PA", expectedName: "bioMérieux", indices: ["CAC Next 20"] },
  { ticker: "BOL.PA", expectedName: "Bolloré", indices: ["CAC Next 20"] },
  { ticker: "AM.PA", expectedName: "Dassault Aviation", indices: ["CAC Next 20"] },
  { ticker: "EDEN.PA", expectedName: "Edenred", indices: ["CAC Next 20"] },
  { ticker: "FGR.PA", expectedName: "Eiffage", indices: ["CAC Next 20"] },
  { ticker: "ERA.PA", expectedName: "Eramet", indices: ["CAC Next 20"] },
  { ticker: "FNAC.PA", expectedName: "Fnac Darty", indices: ["CAC Next 20"] },
  { ticker: "GET.PA", expectedName: "Getlink", indices: ["CAC Next 20"] },
  { ticker: "GTT.PA", expectedName: "GTT", indices: ["CAC Next 20"] },
  { ticker: "NK.PA", expectedName: "Imerys", indices: ["CAC Next 20"] },
  { ticker: "IPS.PA", expectedName: "Ipsos", indices: ["CAC Next 20"] },
  { ticker: "RCO.PA", expectedName: "Rémy Cointreau", indices: ["CAC Next 20"] },
  { ticker: "RXL.PA", expectedName: "Rexel", indices: ["CAC Next 20"] },
  { ticker: "SK.PA", expectedName: "SEB", indices: ["CAC Next 20"] },
  { ticker: "SW.PA", expectedName: "Sodexo", indices: ["CAC Next 20"] },
  { ticker: "SOI.PA", expectedName: "Soitec", indices: ["CAC Next 20"] },
  { ticker: "WLN.PA", expectedName: "Worldline", indices: ["CAC Next 20"] },
]

// ─── CAC Mid 60 (selection of most liquid) ───
const CAC_MID60: TickerEntry[] = [
  { ticker: "AKE.PA", expectedName: "Arkema", indices: ["CAC Mid 60"] },
  { ticker: "BVI.PA", expectedName: "Bureau Veritas", indices: ["CAC Mid 60"] },
  { ticker: "CGG.PA", expectedName: "CGG", indices: ["CAC Mid 60"] },
  { ticker: "COV.PA", expectedName: "Covivio", indices: ["CAC Mid 60"] },
  { ticker: "DIM.PA", expectedName: "Sartorius Stedim", indices: ["CAC Mid 60"] },
  { ticker: "EAPI.PA", expectedName: "Euroapi", indices: ["CAC Mid 60"] },
  { ticker: "FDJ.PA", expectedName: "FDJ", indices: ["CAC Mid 60"] },
  { ticker: "FRVIA.PA", expectedName: "Forvia", indices: ["CAC Mid 60"] },
  { ticker: "FTI", expectedName: "TechnipFMC", indices: ["CAC Mid 60"] },
  { ticker: "GFC.PA", expectedName: "Gecina", indices: ["CAC Mid 60"] },
  { ticker: "GBT.PA", expectedName: "Guerbet", indices: ["CAC Mid 60"] },
  { ticker: "IDL.PA", expectedName: "ID Logistics", indices: ["CAC Mid 60"] },
  { ticker: "IPN.PA", expectedName: "Ipsen", indices: ["CAC Mid 60"] },
  { ticker: "KOF.PA", expectedName: "Kaufman & Broad", indices: ["CAC Mid 60"] },
  { ticker: "MMB.PA", expectedName: "Lagardère", indices: ["CAC Mid 60"] },
  { ticker: "LI.PA", expectedName: "Klepierre", indices: ["CAC Mid 60"] },
  { ticker: "MF.PA", expectedName: "Wendel", indices: ["CAC Mid 60"] },
  { ticker: "NEX.PA", expectedName: "Nexans", indices: ["CAC Mid 60"] },
  { ticker: "NXI.PA", expectedName: "Nexity", indices: ["CAC Mid 60"] },
  { ticker: "OPM.PA", expectedName: "OPmobility", indices: ["CAC Mid 60"] },
  { ticker: "OVH.PA", expectedName: "OVHcloud", indices: ["CAC Mid 60"] },
  { ticker: "POM.PA", expectedName: "Plastic Omnium", indices: ["CAC Mid 60"] },
  { ticker: "QDT.PA", expectedName: "Quadient", indices: ["CAC Mid 60"] },
  { ticker: "RUI.PA", expectedName: "Rubis", indices: ["CAC Mid 60"] },
  { ticker: "SCR.PA", expectedName: "Scor", indices: ["CAC Mid 60"] },
  { ticker: "SOP.PA", expectedName: "Sopra Steria", indices: ["CAC Mid 60"] },
  { ticker: "TFI.PA", expectedName: "TF1", indices: ["CAC Mid 60"] },
  { ticker: "TKO.PA", expectedName: "Tikehau Capital", indices: ["CAC Mid 60"] },
  { ticker: "UBI.PA", expectedName: "Ubisoft", indices: ["CAC Mid 60"] },
  { ticker: "VAL.PA", expectedName: "Vallourec", indices: ["CAC Mid 60"] },
  { ticker: "VIRP.PA", expectedName: "Virbac", indices: ["CAC Mid 60"] },
  { ticker: "VLA.PA", expectedName: "Valneva", indices: ["CAC Mid 60"] },
]

// ─── Germany — DAX 40 ───
const DAX40: TickerEntry[] = [
  { ticker: "ADS.DE", expectedName: "Adidas", indices: ["DAX 40"] },
  { ticker: "AIR.DE", expectedName: "Airbus (Xetra)", indices: ["DAX 40"] },
  { ticker: "ALV.DE", expectedName: "Allianz", indices: ["DAX 40"] },
  { ticker: "BAS.DE", expectedName: "BASF", indices: ["DAX 40"] },
  { ticker: "BAYN.DE", expectedName: "Bayer", indices: ["DAX 40"] },
  { ticker: "BEI.DE", expectedName: "Beiersdorf", indices: ["DAX 40"] },
  { ticker: "BMW.DE", expectedName: "BMW", indices: ["DAX 40"] },
  { ticker: "BNR.DE", expectedName: "Brenntag", indices: ["DAX 40"] },
  { ticker: "1COV.DE", expectedName: "Covestro", indices: ["DAX 40"] },
  { ticker: "DBK.DE", expectedName: "Deutsche Bank", indices: ["DAX 40"] },
  { ticker: "DB1.DE", expectedName: "Deutsche Börse", indices: ["DAX 40"] },
  { ticker: "DHL.DE", expectedName: "DHL Group", indices: ["DAX 40"] },
  { ticker: "DTE.DE", expectedName: "Deutsche Telekom", indices: ["DAX 40"] },
  { ticker: "ENR.DE", expectedName: "Siemens Energy", indices: ["DAX 40"] },
  { ticker: "FRE.DE", expectedName: "Fresenius", indices: ["DAX 40"] },
  { ticker: "HEN3.DE", expectedName: "Henkel", indices: ["DAX 40"] },
  { ticker: "HNR1.DE", expectedName: "Hannover Rück", indices: ["DAX 40"] },
  { ticker: "IFX.DE", expectedName: "Infineon", indices: ["DAX 40"] },
  { ticker: "MBG.DE", expectedName: "Mercedes-Benz", indices: ["DAX 40"] },
  { ticker: "MRK.DE", expectedName: "Merck KGaA", indices: ["DAX 40"] },
  { ticker: "MTX.DE", expectedName: "MTU Aero Engines", indices: ["DAX 40"] },
  { ticker: "MUV2.DE", expectedName: "Munich Re", indices: ["DAX 40"] },
  { ticker: "P911.DE", expectedName: "Porsche AG", indices: ["DAX 40"] },
  { ticker: "PAH3.DE", expectedName: "Porsche Automobil", indices: ["DAX 40"] },
  { ticker: "QIA.DE", expectedName: "Qiagen", indices: ["DAX 40"] },
  { ticker: "RHM.DE", expectedName: "Rheinmetall", indices: ["DAX 40"] },
  { ticker: "RWE.DE", expectedName: "RWE", indices: ["DAX 40"] },
  { ticker: "SAP.DE", expectedName: "SAP", indices: ["DAX 40"] },
  { ticker: "SHL.DE", expectedName: "Siemens Healthineers", indices: ["DAX 40"] },
  { ticker: "SIE.DE", expectedName: "Siemens", indices: ["DAX 40"] },
  { ticker: "SY1.DE", expectedName: "Symrise", indices: ["DAX 40"] },
  { ticker: "VNA.DE", expectedName: "Vonovia", indices: ["DAX 40"] },
  { ticker: "VOW3.DE", expectedName: "Volkswagen", indices: ["DAX 40"] },
  { ticker: "ZAL.DE", expectedName: "Zalando", indices: ["DAX 40"] },
  { ticker: "DHER.DE", expectedName: "Delivery Hero", indices: ["DAX 40"] },
  { ticker: "LEG.DE", expectedName: "LEG Immobilien", indices: ["DAX 40"] },
]

// ─── Netherlands — AEX 25 ───
const AEX25: TickerEntry[] = [
  { ticker: "ADYEN.AS", expectedName: "Adyen", indices: ["AEX 25"] },
  { ticker: "AGN.AS", expectedName: "Aegon", indices: ["AEX 25"] },
  { ticker: "AKZA.AS", expectedName: "Akzo Nobel", indices: ["AEX 25"] },
  { ticker: "ASM.AS", expectedName: "ASM International", indices: ["AEX 25"] },
  { ticker: "ASML.AS", expectedName: "ASML", indices: ["AEX 25"] },
  { ticker: "BESI.AS", expectedName: "BE Semiconductor", indices: ["AEX 25"] },
  { ticker: "HEIA.AS", expectedName: "Heineken", indices: ["AEX 25"] },
  { ticker: "INGA.AS", expectedName: "ING Groep", indices: ["AEX 25"] },
  { ticker: "KPN.AS", expectedName: "KPN", indices: ["AEX 25"] },
  { ticker: "NN.AS", expectedName: "NN Group", indices: ["AEX 25"] },
  { ticker: "PHIA.AS", expectedName: "Philips", indices: ["AEX 25"] },
  { ticker: "PRX.AS", expectedName: "Prosus", indices: ["AEX 25"] },
  { ticker: "RAND.AS", expectedName: "Randstad", indices: ["AEX 25"] },
  { ticker: "UNA.AS", expectedName: "Unilever", indices: ["AEX 25"] },
  { ticker: "WKL.AS", expectedName: "Wolters Kluwer", indices: ["AEX 25"] },
  { ticker: "IMCD.AS", expectedName: "IMCD", indices: ["AEX 25"] },
  { ticker: "SHELL.AS", expectedName: "Shell", indices: ["AEX 25"] },
  { ticker: "ABN.AS", expectedName: "ABN AMRO", indices: ["AEX 25"] },
  { ticker: "AH.AS", expectedName: "Ahold Delhaize", indices: ["AEX 25"] },
  { ticker: "DSFIR.AS", expectedName: "DSM-Firmenich", indices: ["AEX 25"] },
  { ticker: "EXO.AS", expectedName: "Exor", indices: ["AEX 25"] },
  { ticker: "UMG.AS", expectedName: "Universal Music", indices: ["AEX 25"] },
]

// ─── Belgium — BEL 20 ───
const BEL20: TickerEntry[] = [
  { ticker: "ABI.BR", expectedName: "AB InBev", indices: ["BEL 20"] },
  { ticker: "ARGX.BR", expectedName: "argenx", indices: ["BEL 20"] },
  { ticker: "GBLB.BR", expectedName: "GBL", indices: ["BEL 20"] },
  { ticker: "KBC.BR", expectedName: "KBC Group", indices: ["BEL 20"] },
  { ticker: "SOLB.BR", expectedName: "Solvay", indices: ["BEL 20"] },
  { ticker: "UCB.BR", expectedName: "UCB", indices: ["BEL 20"] },
  { ticker: "UMI.BR", expectedName: "Umicore", indices: ["BEL 20"] },
  { ticker: "COFB.BR", expectedName: "Cofinimmo", indices: ["BEL 20"] },
  { ticker: "ACKB.BR", expectedName: "Ackermans & vH", indices: ["BEL 20"] },
  { ticker: "AGS.BR", expectedName: "ageas", indices: ["BEL 20"] },
  { ticker: "PROX.BR", expectedName: "Proximus", indices: ["BEL 20"] },
  { ticker: "WDP.BR", expectedName: "WDP", indices: ["BEL 20"] },
]

// ─── Spain — IBEX 35 (selection) ───
const IBEX: TickerEntry[] = [
  { ticker: "SAN.MC", expectedName: "Banco Santander", indices: ["IBEX 35"] },
  { ticker: "BBVA.MC", expectedName: "BBVA", indices: ["IBEX 35"] },
  { ticker: "ITX.MC", expectedName: "Inditex", indices: ["IBEX 35"] },
  { ticker: "IBE.MC", expectedName: "Iberdrola", indices: ["IBEX 35"] },
  { ticker: "TEF.MC", expectedName: "Telefónica", indices: ["IBEX 35"] },
  { ticker: "REP.MC", expectedName: "Repsol", indices: ["IBEX 35"] },
  { ticker: "AMS.MC", expectedName: "Amadeus IT", indices: ["IBEX 35"] },
  { ticker: "FER.MC", expectedName: "Ferrovial", indices: ["IBEX 35"] },
  { ticker: "CABK.MC", expectedName: "CaixaBank", indices: ["IBEX 35"] },
  { ticker: "ENG.MC", expectedName: "Enagás", indices: ["IBEX 35"] },
  { ticker: "RED.MC", expectedName: "Red Eléctrica", indices: ["IBEX 35"] },
  { ticker: "ACS.MC", expectedName: "ACS", indices: ["IBEX 35"] },
  { ticker: "CLNX.MC", expectedName: "Cellnex", indices: ["IBEX 35"] },
  { ticker: "GRF.MC", expectedName: "Grifols", indices: ["IBEX 35"] },
  { ticker: "MAP.MC", expectedName: "Mapfre", indices: ["IBEX 35"] },
]

// ─── Italy (selection) ───
const ITALY: TickerEntry[] = [
  { ticker: "ENI.MI", expectedName: "Eni", indices: [] },
  { ticker: "ISP.MI", expectedName: "Intesa Sanpaolo", indices: [] },
  { ticker: "ENEL.MI", expectedName: "Enel", indices: [] },
  { ticker: "UCG.MI", expectedName: "UniCredit", indices: [] },
  { ticker: "G.MI", expectedName: "Generali", indices: [] },
  { ticker: "RACE.MI", expectedName: "Ferrari", indices: [] },
  { ticker: "LDO.MI", expectedName: "Leonardo", indices: [] },
  { ticker: "TIT.MI", expectedName: "Telecom Italia", indices: [] },
  { ticker: "BAMI.MI", expectedName: "Banco BPM", indices: [] },
  { ticker: "CPR.MI", expectedName: "Campari", indices: [] },
  { ticker: "TEN.MI", expectedName: "Tenaris", indices: [] },
  { ticker: "SRG.MI", expectedName: "Snam", indices: [] },
  { ticker: "PRY.MI", expectedName: "Prysmian", indices: [] },
  { ticker: "PST.MI", expectedName: "Poste Italiane", indices: [] },
  { ticker: "STMMI.MI", expectedName: "STMicro (Milan)", indices: [] },
]

// ─── Portugal ───
const PORTUGAL: TickerEntry[] = [
  { ticker: "EDP.LS", expectedName: "EDP", indices: [] },
  { ticker: "GALP.LS", expectedName: "Galp Energia", indices: [] },
  { ticker: "JMT.LS", expectedName: "Jerónimo Martins", indices: [] },
  { ticker: "SON.LS", expectedName: "Sonae", indices: [] },
]

// ─── Finland ───
const FINLAND: TickerEntry[] = [
  { ticker: "NOKIA.HE", expectedName: "Nokia", indices: [] },
  { ticker: "SAMPO.HE", expectedName: "Sampo", indices: [] },
  { ticker: "FORTUM.HE", expectedName: "Fortum", indices: [] },
  { ticker: "UPM.HE", expectedName: "UPM-Kymmene", indices: [] },
  { ticker: "STERV.HE", expectedName: "Stora Enso", indices: [] },
  { ticker: "NESTE.HE", expectedName: "Neste", indices: [] },
  { ticker: "WRT1V.HE", expectedName: "Wärtsilä", indices: [] },
  { ticker: "KNEBV.HE", expectedName: "Kone", indices: [] },
  { ticker: "ELISA.HE", expectedName: "Elisa", indices: [] },
]

// ─── Ireland ───
const IRELAND: TickerEntry[] = [
  { ticker: "CRH.L", expectedName: "CRH", indices: [] },
  { ticker: "SKG.L", expectedName: "Smurfit Kappa", indices: [] },
  { ticker: "KYGA.L", expectedName: "Kerry Group", indices: [] },
  { ticker: "BIRG.L", expectedName: "Bank of Ireland", indices: [] },
]

// ─── Austria ───
const AUSTRIA: TickerEntry[] = [
  { ticker: "VOE.VI", expectedName: "Voestalpine", indices: [] },
  { ticker: "OMV.VI", expectedName: "OMV", indices: [] },
  { ticker: "EBS.VI", expectedName: "Erste Group", indices: [] },
  { ticker: "VER.VI", expectedName: "Verbund", indices: [] },
  { ticker: "WIE.VI", expectedName: "Wienerberger", indices: [] },
]

// ─── USA — S&P 500 Top 100 ───
const SP500: TickerEntry[] = [
  { ticker: "AAPL", expectedName: "Apple", indices: ["S&P 500"] },
  { ticker: "MSFT", expectedName: "Microsoft", indices: ["S&P 500"] },
  { ticker: "NVDA", expectedName: "NVIDIA", indices: ["S&P 500"] },
  { ticker: "AMZN", expectedName: "Amazon", indices: ["S&P 500"] },
  { ticker: "META", expectedName: "Meta Platforms", indices: ["S&P 500"] },
  { ticker: "GOOGL", expectedName: "Alphabet (Class A)", indices: ["S&P 500"] },
  { ticker: "GOOG", expectedName: "Alphabet (Class C)", indices: ["S&P 500"] },
  { ticker: "BRK-B", expectedName: "Berkshire Hathaway", indices: ["S&P 500"] },
  { ticker: "TSLA", expectedName: "Tesla", indices: ["S&P 500"] },
  { ticker: "LLY", expectedName: "Eli Lilly", indices: ["S&P 500"] },
  { ticker: "AVGO", expectedName: "Broadcom", indices: ["S&P 500"] },
  { ticker: "V", expectedName: "Visa", indices: ["S&P 500"] },
  { ticker: "JPM", expectedName: "JPMorgan Chase", indices: ["S&P 500"] },
  { ticker: "UNH", expectedName: "UnitedHealth Group", indices: ["S&P 500"] },
  { ticker: "WMT", expectedName: "Walmart", indices: ["S&P 500"] },
  { ticker: "MA", expectedName: "Mastercard", indices: ["S&P 500"] },
  { ticker: "XOM", expectedName: "Exxon Mobil", indices: ["S&P 500"] },
  { ticker: "JNJ", expectedName: "Johnson & Johnson", indices: ["S&P 500"] },
  { ticker: "PG", expectedName: "Procter & Gamble", indices: ["S&P 500"] },
  { ticker: "HD", expectedName: "Home Depot", indices: ["S&P 500"] },
  { ticker: "COST", expectedName: "Costco Wholesale", indices: ["S&P 500"] },
  { ticker: "MRK", expectedName: "Merck & Co.", indices: ["S&P 500"] },
  { ticker: "ABBV", expectedName: "AbbVie", indices: ["S&P 500"] },
  { ticker: "CRM", expectedName: "Salesforce", indices: ["S&P 500"] },
  { ticker: "CVX", expectedName: "Chevron", indices: ["S&P 500"] },
  { ticker: "AMD", expectedName: "Advanced Micro Devices", indices: ["S&P 500"] },
  { ticker: "NFLX", expectedName: "Netflix", indices: ["S&P 500"] },
  { ticker: "PEP", expectedName: "PepsiCo", indices: ["S&P 500"] },
  { ticker: "KO", expectedName: "Coca-Cola", indices: ["S&P 500"] },
  { ticker: "BAC", expectedName: "Bank of America", indices: ["S&P 500"] },
  { ticker: "ADBE", expectedName: "Adobe", indices: ["S&P 500"] },
  { ticker: "LIN", expectedName: "Linde", indices: ["S&P 500"] },
  { ticker: "TMO", expectedName: "Thermo Fisher Scientific", indices: ["S&P 500"] },
  { ticker: "MCD", expectedName: "McDonald's", indices: ["S&P 500"] },
  { ticker: "CSCO", expectedName: "Cisco Systems", indices: ["S&P 500"] },
  { ticker: "INTU", expectedName: "Intuit", indices: ["S&P 500"] },
  { ticker: "ABT", expectedName: "Abbott Laboratories", indices: ["S&P 500"] },
  { ticker: "QCOM", expectedName: "Qualcomm", indices: ["S&P 500"] },
  { ticker: "WFC", expectedName: "Wells Fargo", indices: ["S&P 500"] },
  { ticker: "DHR", expectedName: "Danaher", indices: ["S&P 500"] },
  { ticker: "GE", expectedName: "General Electric", indices: ["S&P 500"] },
  { ticker: "IBM", expectedName: "IBM", indices: ["S&P 500"] },
  { ticker: "AXP", expectedName: "American Express", indices: ["S&P 500"] },
  { ticker: "CAT", expectedName: "Caterpillar", indices: ["S&P 500"] },
  { ticker: "VZ", expectedName: "Verizon", indices: ["S&P 500"] },
  { ticker: "TXN", expectedName: "Texas Instruments", indices: ["S&P 500"] },
  { ticker: "DIS", expectedName: "Walt Disney", indices: ["S&P 500"] },
  { ticker: "AMGN", expectedName: "Amgen", indices: ["S&P 500"] },
  { ticker: "PFE", expectedName: "Pfizer", indices: ["S&P 500"] },
  { ticker: "NOW", expectedName: "ServiceNow", indices: ["S&P 500"] },
  // 51–100
  { ticker: "ORCL", expectedName: "Oracle", indices: ["S&P 500"] },
  { ticker: "GS", expectedName: "Goldman Sachs", indices: ["S&P 500"] },
  { ticker: "MS", expectedName: "Morgan Stanley", indices: ["S&P 500"] },
  { ticker: "RTX", expectedName: "RTX Corporation", indices: ["S&P 500"] },
  { ticker: "ISRG", expectedName: "Intuitive Surgical", indices: ["S&P 500"] },
  { ticker: "BKNG", expectedName: "Booking Holdings", indices: ["S&P 500"] },
  { ticker: "BLK", expectedName: "BlackRock", indices: ["S&P 500"] },
  { ticker: "SPGI", expectedName: "S&P Global", indices: ["S&P 500"] },
  { ticker: "T", expectedName: "AT&T", indices: ["S&P 500"] },
  { ticker: "C", expectedName: "Citigroup", indices: ["S&P 500"] },
  { ticker: "SCHW", expectedName: "Charles Schwab", indices: ["S&P 500"] },
  { ticker: "ADP", expectedName: "Automatic Data Processing", indices: ["S&P 500"] },
  { ticker: "TMUS", expectedName: "T-Mobile US", indices: ["S&P 500"] },
  { ticker: "BMY", expectedName: "Bristol-Myers Squibb", indices: ["S&P 500"] },
  { ticker: "SYK", expectedName: "Stryker", indices: ["S&P 500"] },
  { ticker: "DE", expectedName: "Deere & Company", indices: ["S&P 500"] },
  { ticker: "MU", expectedName: "Micron Technology", indices: ["S&P 500"] },
  { ticker: "PANW", expectedName: "Palo Alto Networks", indices: ["S&P 500"] },
  { ticker: "COP", expectedName: "ConocoPhillips", indices: ["S&P 500"] },
  { ticker: "SBUX", expectedName: "Starbucks", indices: ["S&P 500"] },
  { ticker: "CI", expectedName: "Cigna Group", indices: ["S&P 500"] },
  { ticker: "ELV", expectedName: "Elevance Health", indices: ["S&P 500"] },
  { ticker: "GILD", expectedName: "Gilead Sciences", indices: ["S&P 500"] },
  { ticker: "AMT", expectedName: "American Tower", indices: ["S&P 500"] },
  { ticker: "TJX", expectedName: "TJX Companies", indices: ["S&P 500"] },
  { ticker: "USB", expectedName: "U.S. Bancorp", indices: ["S&P 500"] },
  { ticker: "PNC", expectedName: "PNC Financial Services", indices: ["S&P 500"] },
  { ticker: "ETN", expectedName: "Eaton Corporation", indices: ["S&P 500"] },
  { ticker: "LMT", expectedName: "Lockheed Martin", indices: ["S&P 500"] },
  { ticker: "NOC", expectedName: "Northrop Grumman", indices: ["S&P 500"] },
  { ticker: "DUK", expectedName: "Duke Energy", indices: ["S&P 500"] },
  { ticker: "BA", expectedName: "Boeing", indices: ["S&P 500"] },
  { ticker: "INTC", expectedName: "Intel", indices: ["S&P 500"] },
  { ticker: "ICE", expectedName: "Intercontinental Exchange", indices: ["S&P 500"] },
  { ticker: "CME", expectedName: "CME Group", indices: ["S&P 500"] },
  { ticker: "PLD", expectedName: "Prologis", indices: ["S&P 500"] },
  { ticker: "MDLZ", expectedName: "Mondelez International", indices: ["S&P 500"] },
  { ticker: "ZTS", expectedName: "Zoetis", indices: ["S&P 500"] },
  { ticker: "SHW", expectedName: "Sherwin-Williams", indices: ["S&P 500"] },
  { ticker: "SO", expectedName: "Southern Company", indices: ["S&P 500"] },
  { ticker: "EOG", expectedName: "EOG Resources", indices: ["S&P 500"] },
  { ticker: "MO", expectedName: "Altria Group", indices: ["S&P 500"] },
  { ticker: "APH", expectedName: "Amphenol", indices: ["S&P 500"] },
  { ticker: "EMR", expectedName: "Emerson Electric", indices: ["S&P 500"] },
  { ticker: "CL", expectedName: "Colgate-Palmolive", indices: ["S&P 500"] },
  { ticker: "GM", expectedName: "General Motors", indices: ["S&P 500"] },
  { ticker: "F", expectedName: "Ford Motor", indices: ["S&P 500"] },
  { ticker: "TGT", expectedName: "Target", indices: ["S&P 500"] },
  { ticker: "MMM", expectedName: "3M", indices: ["S&P 500"] },
  { ticker: "CB", expectedName: "Chubb", indices: ["S&P 500"] },
]

// ─── China — Top 100 (Hong Kong + ADRs US) ───
const CHINA_TOP100: TickerEntry[] = [
  // HK-listed
  { ticker: "0700.HK", expectedName: "Tencent", indices: ["Chine Top 100"] },
  { ticker: "0941.HK", expectedName: "China Mobile", indices: ["Chine Top 100"] },
  { ticker: "1398.HK", expectedName: "ICBC", indices: ["Chine Top 100"] },
  { ticker: "0939.HK", expectedName: "CCB", indices: ["Chine Top 100"] },
  { ticker: "3988.HK", expectedName: "Bank of China", indices: ["Chine Top 100"] },
  { ticker: "2318.HK", expectedName: "Ping An Insurance", indices: ["Chine Top 100"] },
  { ticker: "0883.HK", expectedName: "CNOOC", indices: ["Chine Top 100"] },
  { ticker: "0386.HK", expectedName: "Sinopec", indices: ["Chine Top 100"] },
  { ticker: "0857.HK", expectedName: "PetroChina", indices: ["Chine Top 100"] },
  { ticker: "1810.HK", expectedName: "Xiaomi", indices: ["Chine Top 100"] },
  { ticker: "3690.HK", expectedName: "Meituan", indices: ["Chine Top 100"] },
  { ticker: "9988.HK", expectedName: "Alibaba (HK)", indices: ["Chine Top 100"] },
  { ticker: "9618.HK", expectedName: "JD.com (HK)", indices: ["Chine Top 100"] },
  { ticker: "9888.HK", expectedName: "Baidu (HK)", indices: ["Chine Top 100"] },
  { ticker: "9999.HK", expectedName: "NetEase (HK)", indices: ["Chine Top 100"] },
  { ticker: "9961.HK", expectedName: "Trip.com (HK)", indices: ["Chine Top 100"] },
  { ticker: "0175.HK", expectedName: "Geely Automobile", indices: ["Chine Top 100"] },
  { ticker: "1024.HK", expectedName: "Kuaishou", indices: ["Chine Top 100"] },
  { ticker: "0388.HK", expectedName: "HKEX", indices: ["Chine Top 100"] },
  { ticker: "2020.HK", expectedName: "ANTA Sports", indices: ["Chine Top 100"] },
  { ticker: "1211.HK", expectedName: "BYD (HK)", indices: ["Chine Top 100"] },
  { ticker: "2269.HK", expectedName: "Wuxi Biologics", indices: ["Chine Top 100"] },
  { ticker: "0762.HK", expectedName: "China Unicom", indices: ["Chine Top 100"] },
  { ticker: "0728.HK", expectedName: "China Telecom (HK)", indices: ["Chine Top 100"] },
  { ticker: "2313.HK", expectedName: "Shenzhou International", indices: ["Chine Top 100"] },
  { ticker: "0669.HK", expectedName: "Techtronic Industries", indices: ["Chine Top 100"] },
  { ticker: "2382.HK", expectedName: "Sunny Optical", indices: ["Chine Top 100"] },
  { ticker: "6690.HK", expectedName: "Haier Smart Home (HK)", indices: ["Chine Top 100"] },
  { ticker: "9868.HK", expectedName: "XPeng (HK)", indices: ["Chine Top 100"] },
  { ticker: "2015.HK", expectedName: "Li Auto (HK)", indices: ["Chine Top 100"] },
  { ticker: "6862.HK", expectedName: "Haidilao", indices: ["Chine Top 100"] },
  { ticker: "9901.HK", expectedName: "New Oriental (HK)", indices: ["Chine Top 100"] },
  { ticker: "0066.HK", expectedName: "MTR Corporation", indices: ["Chine Top 100"] },
  { ticker: "1093.HK", expectedName: "CSPC Pharma", indices: ["Chine Top 100"] },
  { ticker: "3968.HK", expectedName: "China Merchants Bank", indices: ["Chine Top 100"] },
  { ticker: "2628.HK", expectedName: "China Life Insurance", indices: ["Chine Top 100"] },
  { ticker: "6098.HK", expectedName: "Country Garden Services", indices: ["Chine Top 100"] },
  { ticker: "0002.HK", expectedName: "CLP Holdings", indices: ["Chine Top 100"] },
  { ticker: "0012.HK", expectedName: "Henderson Land", indices: ["Chine Top 100"] },
  { ticker: "0016.HK", expectedName: "Sun Hung Kai Properties", indices: ["Chine Top 100"] },
  { ticker: "1177.HK", expectedName: "Sino Biopharmaceutical", indices: ["Chine Top 100"] },
  { ticker: "0688.HK", expectedName: "China Overseas Land", indices: ["Chine Top 100"] },
  { ticker: "9698.HK", expectedName: "GDS Holdings (HK)", indices: ["Chine Top 100"] },
  { ticker: "0960.HK", expectedName: "Longfor Properties", indices: ["Chine Top 100"] },
  { ticker: "1997.HK", expectedName: "Wharf REIC", indices: ["Chine Top 100"] },
  { ticker: "0011.HK", expectedName: "Hang Seng Bank", indices: ["Chine Top 100"] },
  // US ADRs
  { ticker: "BABA", expectedName: "Alibaba Group", indices: ["Chine Top 100"] },
  { ticker: "PDD", expectedName: "PDD Holdings", indices: ["Chine Top 100"] },
  { ticker: "JD", expectedName: "JD.com", indices: ["Chine Top 100"] },
  { ticker: "BIDU", expectedName: "Baidu", indices: ["Chine Top 100"] },
  { ticker: "NTES", expectedName: "NetEase", indices: ["Chine Top 100"] },
  { ticker: "NIO", expectedName: "NIO", indices: ["Chine Top 100"] },
  { ticker: "XPEV", expectedName: "XPeng", indices: ["Chine Top 100"] },
  { ticker: "LI", expectedName: "Li Auto", indices: ["Chine Top 100"] },
  { ticker: "TME", expectedName: "Tencent Music", indices: ["Chine Top 100"] },
  { ticker: "YUMC", expectedName: "Yum China", indices: ["Chine Top 100"] },
  { ticker: "VIPS", expectedName: "Vipshop", indices: ["Chine Top 100"] },
  { ticker: "IQ", expectedName: "iQIYI", indices: ["Chine Top 100"] },
  { ticker: "FUTU", expectedName: "Futu Holdings", indices: ["Chine Top 100"] },
  { ticker: "TAL", expectedName: "TAL Education", indices: ["Chine Top 100"] },
]

// ─── Japan — Nikkei / TSE Top 80 ───
const JAPAN_TOP80: TickerEntry[] = [
  { ticker: "7203.T", expectedName: "Toyota Motor", indices: ["Japon Top 100"] },
  { ticker: "9432.T", expectedName: "NTT", indices: ["Japon Top 100"] },
  { ticker: "8306.T", expectedName: "Mitsubishi UFJ Financial", indices: ["Japon Top 100"] },
  { ticker: "6758.T", expectedName: "Sony Group", indices: ["Japon Top 100"] },
  { ticker: "9984.T", expectedName: "SoftBank Group", indices: ["Japon Top 100"] },
  { ticker: "6861.T", expectedName: "Keyence", indices: ["Japon Top 100"] },
  { ticker: "7974.T", expectedName: "Nintendo", indices: ["Japon Top 100"] },
  { ticker: "8035.T", expectedName: "Tokyo Electron", indices: ["Japon Top 100"] },
  { ticker: "9433.T", expectedName: "KDDI", indices: ["Japon Top 100"] },
  { ticker: "7267.T", expectedName: "Honda Motor", indices: ["Japon Top 100"] },
  { ticker: "4502.T", expectedName: "Takeda Pharmaceutical", indices: ["Japon Top 100"] },
  { ticker: "6501.T", expectedName: "Hitachi", indices: ["Japon Top 100"] },
  { ticker: "6954.T", expectedName: "Fanuc", indices: ["Japon Top 100"] },
  { ticker: "4063.T", expectedName: "Shin-Etsu Chemical", indices: ["Japon Top 100"] },
  { ticker: "6367.T", expectedName: "Daikin Industries", indices: ["Japon Top 100"] },
  { ticker: "8316.T", expectedName: "Sumitomo Mitsui Financial", indices: ["Japon Top 100"] },
  { ticker: "4661.T", expectedName: "Oriental Land", indices: ["Japon Top 100"] },
  { ticker: "7741.T", expectedName: "HOYA", indices: ["Japon Top 100"] },
  { ticker: "6981.T", expectedName: "Murata Manufacturing", indices: ["Japon Top 100"] },
  { ticker: "4519.T", expectedName: "Chugai Pharmaceutical", indices: ["Japon Top 100"] },
  { ticker: "2914.T", expectedName: "Japan Tobacco", indices: ["Japon Top 100"] },
  { ticker: "4568.T", expectedName: "Daiichi Sankyo", indices: ["Japon Top 100"] },
  { ticker: "9022.T", expectedName: "Central Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "8411.T", expectedName: "Mizuho Financial Group", indices: ["Japon Top 100"] },
  { ticker: "7751.T", expectedName: "Canon", indices: ["Japon Top 100"] },
  { ticker: "9434.T", expectedName: "SoftBank Corp", indices: ["Japon Top 100"] },
  { ticker: "6702.T", expectedName: "Fujitsu", indices: ["Japon Top 100"] },
  { ticker: "6503.T", expectedName: "Mitsubishi Electric", indices: ["Japon Top 100"] },
  { ticker: "4523.T", expectedName: "Eisai", indices: ["Japon Top 100"] },
  { ticker: "8058.T", expectedName: "Mitsubishi Corporation", indices: ["Japon Top 100"] },
  { ticker: "8031.T", expectedName: "Mitsui & Co", indices: ["Japon Top 100"] },
  { ticker: "9020.T", expectedName: "East Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "8801.T", expectedName: "Mitsui Fudosan", indices: ["Japon Top 100"] },
  { ticker: "5401.T", expectedName: "Nippon Steel", indices: ["Japon Top 100"] },
  { ticker: "9983.T", expectedName: "Fast Retailing", indices: ["Japon Top 100"] },
  { ticker: "4911.T", expectedName: "Shiseido", indices: ["Japon Top 100"] },
  { ticker: "2802.T", expectedName: "Ajinomoto", indices: ["Japon Top 100"] },
  { ticker: "7733.T", expectedName: "Olympus", indices: ["Japon Top 100"] },
  { ticker: "6752.T", expectedName: "Panasonic Holdings", indices: ["Japon Top 100"] },
  { ticker: "3382.T", expectedName: "Seven & I Holdings", indices: ["Japon Top 100"] },
  { ticker: "4452.T", expectedName: "Kao", indices: ["Japon Top 100"] },
  { ticker: "2503.T", expectedName: "Kirin Holdings", indices: ["Japon Top 100"] },
  { ticker: "9101.T", expectedName: "Nippon Yusen", indices: ["Japon Top 100"] },
  { ticker: "9104.T", expectedName: "Mitsui OSK Lines", indices: ["Japon Top 100"] },
  { ticker: "7011.T", expectedName: "Mitsubishi Heavy Industries", indices: ["Japon Top 100"] },
  { ticker: "4901.T", expectedName: "Fujifilm Holdings", indices: ["Japon Top 100"] },
  { ticker: "7201.T", expectedName: "Nissan Motor", indices: ["Japon Top 100"] },
  { ticker: "8002.T", expectedName: "Marubeni", indices: ["Japon Top 100"] },
  { ticker: "8053.T", expectedName: "Sumitomo Corporation", indices: ["Japon Top 100"] },
  { ticker: "6857.T", expectedName: "Advantest", indices: ["Japon Top 100"] },
  { ticker: "6723.T", expectedName: "Renesas Electronics", indices: ["Japon Top 100"] },
  { ticker: "6762.T", expectedName: "TDK", indices: ["Japon Top 100"] },
  { ticker: "5108.T", expectedName: "Bridgestone", indices: ["Japon Top 100"] },
  { ticker: "4543.T", expectedName: "Terumo", indices: ["Japon Top 100"] },
  { ticker: "4578.T", expectedName: "Otsuka Holdings", indices: ["Japon Top 100"] },
  { ticker: "8766.T", expectedName: "Tokio Marine Holdings", indices: ["Japon Top 100"] },
  { ticker: "8309.T", expectedName: "Sumitomo Mitsui Trust", indices: ["Japon Top 100"] },
  { ticker: "6971.T", expectedName: "Kyocera", indices: ["Japon Top 100"] },
  { ticker: "4062.T", expectedName: "Ibiden", indices: ["Japon Top 100"] },
  { ticker: "9021.T", expectedName: "West Japan Railway", indices: ["Japon Top 100"] },
  { ticker: "6902.T", expectedName: "Denso", indices: ["Japon Top 100"] },
  { ticker: "3407.T", expectedName: "Asahi Kasei", indices: ["Japon Top 100"] },
  { ticker: "9107.T", expectedName: "Kawasaki Kisen Kaisha", indices: ["Japon Top 100"] },
  { ticker: "4507.T", expectedName: "Shionogi", indices: ["Japon Top 100"] },
  { ticker: "7735.T", expectedName: "Screen Holdings", indices: ["Japon Top 100"] },
  { ticker: "8028.T", expectedName: "FamilyMart (FJ)", indices: ["Japon Top 100"] },
  { ticker: "2267.T", expectedName: "Yakult Honsha", indices: ["Japon Top 100"] },
  { ticker: "2501.T", expectedName: "Sapporo Holdings", indices: ["Japon Top 100"] },
  { ticker: "4151.T", expectedName: "Kyowa Kirin", indices: ["Japon Top 100"] },
  { ticker: "3659.T", expectedName: "Nexon", indices: ["Japon Top 100"] },
  { ticker: "9613.T", expectedName: "NTT Data Group", indices: ["Japon Top 100"] },
  { ticker: "6724.T", expectedName: "Seiko Epson", indices: ["Japon Top 100"] },
  { ticker: "5803.T", expectedName: "Furukawa Electric", indices: ["Japon Top 100"] },
  { ticker: "4183.T", expectedName: "Mitsui Chemicals", indices: ["Japon Top 100"] },
  { ticker: "7261.T", expectedName: "Mazda Motor", indices: ["Japon Top 100"] },
  { ticker: "2282.T", expectedName: "NH Foods", indices: ["Japon Top 100"] },
  { ticker: "4004.T", expectedName: "Resonac Holdings", indices: ["Japon Top 100"] },
  { ticker: "8308.T", expectedName: "Resona Holdings", indices: ["Japon Top 100"] },
]

// ─── UK — FTSE 100 (60 largest) ───
const FTSE100: TickerEntry[] = [
  { ticker: "AZN.L", expectedName: "AstraZeneca", indices: ["FTSE 100"] },
  { ticker: "SHEL.L", expectedName: "Shell", indices: ["FTSE 100"] },
  { ticker: "HSBA.L", expectedName: "HSBC Holdings", indices: ["FTSE 100"] },
  { ticker: "ULVR.L", expectedName: "Unilever", indices: ["FTSE 100"] },
  { ticker: "BP.L", expectedName: "BP", indices: ["FTSE 100"] },
  { ticker: "RIO.L", expectedName: "Rio Tinto", indices: ["FTSE 100"] },
  { ticker: "GSK.L", expectedName: "GSK", indices: ["FTSE 100"] },
  { ticker: "DGE.L", expectedName: "Diageo", indices: ["FTSE 100"] },
  { ticker: "REL.L", expectedName: "RELX", indices: ["FTSE 100"] },
  { ticker: "LSEG.L", expectedName: "London Stock Exchange Group", indices: ["FTSE 100"] },
  { ticker: "NG.L", expectedName: "National Grid", indices: ["FTSE 100"] },
  { ticker: "BATS.L", expectedName: "British American Tobacco", indices: ["FTSE 100"] },
  { ticker: "BA.L", expectedName: "BAE Systems", indices: ["FTSE 100"] },
  { ticker: "RKT.L", expectedName: "Reckitt Benckiser", indices: ["FTSE 100"] },
  { ticker: "HLN.L", expectedName: "Haleon", indices: ["FTSE 100"] },
  { ticker: "PRU.L", expectedName: "Prudential", indices: ["FTSE 100"] },
  { ticker: "IMB.L", expectedName: "Imperial Brands", indices: ["FTSE 100"] },
  { ticker: "CPG.L", expectedName: "Compass Group", indices: ["FTSE 100"] },
  { ticker: "EXPN.L", expectedName: "Experian", indices: ["FTSE 100"] },
  { ticker: "FLTR.L", expectedName: "Flutter Entertainment", indices: ["FTSE 100"] },
  { ticker: "AAL.L", expectedName: "Anglo American", indices: ["FTSE 100"] },
  { ticker: "GLEN.L", expectedName: "Glencore", indices: ["FTSE 100"] },
  { ticker: "NWG.L", expectedName: "NatWest Group", indices: ["FTSE 100"] },
  { ticker: "LLOY.L", expectedName: "Lloyds Banking Group", indices: ["FTSE 100"] },
  { ticker: "BARC.L", expectedName: "Barclays", indices: ["FTSE 100"] },
  { ticker: "STAN.L", expectedName: "Standard Chartered", indices: ["FTSE 100"] },
  { ticker: "III.L", expectedName: "3i Group", indices: ["FTSE 100"] },
  { ticker: "WPP.L", expectedName: "WPP", indices: ["FTSE 100"] },
  { ticker: "SGE.L", expectedName: "Sage Group", indices: ["FTSE 100"] },
  { ticker: "AUTO.L", expectedName: "Auto Trader Group", indices: ["FTSE 100"] },
  { ticker: "HLMA.L", expectedName: "Halma", indices: ["FTSE 100"] },
  { ticker: "VOD.L", expectedName: "Vodafone", indices: ["FTSE 100"] },
  { ticker: "BT-A.L", expectedName: "BT Group", indices: ["FTSE 100"] },
  { ticker: "TSCO.L", expectedName: "Tesco", indices: ["FTSE 100"] },
  { ticker: "ABF.L", expectedName: "Associated British Foods", indices: ["FTSE 100"] },
  { ticker: "NXT.L", expectedName: "Next", indices: ["FTSE 100"] },
  { ticker: "MKS.L", expectedName: "Marks & Spencer", indices: ["FTSE 100"] },
  { ticker: "SBRY.L", expectedName: "J Sainsbury", indices: ["FTSE 100"] },
  { ticker: "JD.L", expectedName: "JD Sports Fashion", indices: ["FTSE 100"] },
  { ticker: "KGF.L", expectedName: "Kingfisher", indices: ["FTSE 100"] },
  { ticker: "IHG.L", expectedName: "InterContinental Hotels Group", indices: ["FTSE 100"] },
  { ticker: "WTB.L", expectedName: "Whitbread", indices: ["FTSE 100"] },
  { ticker: "RTO.L", expectedName: "Rentokil Initial", indices: ["FTSE 100"] },
  { ticker: "AHT.L", expectedName: "Ashtead Group", indices: ["FTSE 100"] },
  { ticker: "CNA.L", expectedName: "Centrica", indices: ["FTSE 100"] },
  { ticker: "SSE.L", expectedName: "SSE", indices: ["FTSE 100"] },
  { ticker: "UU.L", expectedName: "United Utilities", indices: ["FTSE 100"] },
  { ticker: "SVT.L", expectedName: "Severn Trent", indices: ["FTSE 100"] },
  { ticker: "SGRO.L", expectedName: "Segro", indices: ["FTSE 100"] },
  { ticker: "LAND.L", expectedName: "Land Securities", indices: ["FTSE 100"] },
  { ticker: "RR.L", expectedName: "Rolls-Royce Holdings", indices: ["FTSE 100"] },
  { ticker: "IAG.L", expectedName: "International Airlines Group", indices: ["FTSE 100"] },
  { ticker: "MNDI.L", expectedName: "Mondi", indices: ["FTSE 100"] },
  { ticker: "CRDA.L", expectedName: "Croda International", indices: ["FTSE 100"] },
  { ticker: "ENT.L", expectedName: "Entain", indices: ["FTSE 100"] },
  { ticker: "ITRK.L", expectedName: "Intertek Group", indices: ["FTSE 100"] },
  { ticker: "PSON.L", expectedName: "Pearson", indices: ["FTSE 100"] },
  { ticker: "SDR.L", expectedName: "Schroders", indices: ["FTSE 100"] },
  { ticker: "ABRDN.L", expectedName: "abrdn", indices: ["FTSE 100"] },
  { ticker: "MNG.L", expectedName: "M&G", indices: ["FTSE 100"] },
  { ticker: "ANTO.L", expectedName: "Antofagasta", indices: ["FTSE 100"] },
]

// ─── Switzerland — SMI 20 + SMIM selection ───
const SMI: TickerEntry[] = [
  { ticker: "NESN.SW", expectedName: "Nestlé", indices: ["SMI"] },
  { ticker: "ROG.SW", expectedName: "Roche Holding", indices: ["SMI"] },
  { ticker: "NOVN.SW", expectedName: "Novartis", indices: ["SMI"] },
  { ticker: "ABBN.SW", expectedName: "ABB", indices: ["SMI"] },
  { ticker: "LONN.SW", expectedName: "Lonza Group", indices: ["SMI"] },
  { ticker: "CFR.SW", expectedName: "Richemont", indices: ["SMI"] },
  { ticker: "GIVN.SW", expectedName: "Givaudan", indices: ["SMI"] },
  { ticker: "SIKA.SW", expectedName: "Sika", indices: ["SMI"] },
  { ticker: "ALC.SW", expectedName: "Alcon", indices: ["SMI"] },
  { ticker: "KNIN.SW", expectedName: "Kuehne+Nagel", indices: ["SMI"] },
  { ticker: "SCMN.SW", expectedName: "Swisscom", indices: ["SMI"] },
  { ticker: "SREN.SW", expectedName: "Swiss Re", indices: ["SMI"] },
  { ticker: "ZURN.SW", expectedName: "Zurich Insurance Group", indices: ["SMI"] },
  { ticker: "HOLN.SW", expectedName: "Holcim", indices: ["SMI"] },
  { ticker: "PGHN.SW", expectedName: "Partners Group", indices: ["SMI"] },
  { ticker: "GEBN.SW", expectedName: "Geberit", indices: ["SMI"] },
  { ticker: "SLHN.SW", expectedName: "Swiss Life Holding", indices: ["SMI"] },
  { ticker: "BALN.SW", expectedName: "Baloise Holding", indices: ["SMI"] },
  { ticker: "UHR.SW", expectedName: "Swatch Group", indices: ["SMI"] },
  { ticker: "SGSN.SW", expectedName: "SGS", indices: ["SMI"] },
  // SMIM selection
  { ticker: "STMN.SW", expectedName: "Straumann Holding", indices: ["SMIM"] },
  { ticker: "SOON.SW", expectedName: "Sonova Holding", indices: ["SMIM"] },
  { ticker: "OERLN.SW", expectedName: "OC Oerlikon", indices: ["SMIM"] },
  { ticker: "DKSH.SW", expectedName: "DKSH Holding", indices: ["SMIM"] },
  { ticker: "HELN.SW", expectedName: "Helvetia Holding", indices: ["SMIM"] },
]

// ─── Sweden — OMX Stockholm 30 ───
const OMX_SE: TickerEntry[] = [
  { ticker: "VOLV-B.ST", expectedName: "Volvo B", indices: ["OMX SE 30"] },
  { ticker: "ERIC-B.ST", expectedName: "Ericsson B", indices: ["OMX SE 30"] },
  { ticker: "ATCO-A.ST", expectedName: "Atlas Copco A", indices: ["OMX SE 30"] },
  { ticker: "ATCO-B.ST", expectedName: "Atlas Copco B", indices: ["OMX SE 30"] },
  { ticker: "INVE-B.ST", expectedName: "Investor B", indices: ["OMX SE 30"] },
  { ticker: "SAND.ST", expectedName: "Sandvik", indices: ["OMX SE 30"] },
  { ticker: "ALFA.ST", expectedName: "Alfa Laval", indices: ["OMX SE 30"] },
  { ticker: "SEB-A.ST", expectedName: "SEB A", indices: ["OMX SE 30"] },
  { ticker: "SHB-A.ST", expectedName: "Handelsbanken A", indices: ["OMX SE 30"] },
  { ticker: "SWED-A.ST", expectedName: "Swedbank A", indices: ["OMX SE 30"] },
  { ticker: "SSAB-A.ST", expectedName: "SSAB A", indices: ["OMX SE 30"] },
  { ticker: "NIBE-B.ST", expectedName: "NIBE Industrier B", indices: ["OMX SE 30"] },
  { ticker: "TEL2-B.ST", expectedName: "Tele2 B", indices: ["OMX SE 30"] },
  { ticker: "TELIA.ST", expectedName: "Telia Company", indices: ["OMX SE 30"] },
  { ticker: "SKF-B.ST", expectedName: "SKF B", indices: ["OMX SE 30"] },
  { ticker: "EVO.ST", expectedName: "Evolution AB", indices: ["OMX SE 30"] },
  { ticker: "GETI-B.ST", expectedName: "Getinge B", indices: ["OMX SE 30"] },
  { ticker: "HEXA-B.ST", expectedName: "Hexagon B", indices: ["OMX SE 30"] },
  { ticker: "SAAB-B.ST", expectedName: "Saab B", indices: ["OMX SE 30"] },
  { ticker: "BOL.ST", expectedName: "Boliden", indices: ["OMX SE 30"] },
  { ticker: "ESSITY-B.ST", expectedName: "Essity B", indices: ["OMX SE 30"] },
  { ticker: "HM-B.ST", expectedName: "H&M B", indices: ["OMX SE 30"] },
  { ticker: "INDU-C.ST", expectedName: "Industrivärden C", indices: ["OMX SE 30"] },
  { ticker: "HUSQ-B.ST", expectedName: "Husqvarna B", indices: ["OMX SE 30"] },
  { ticker: "NDA-SE.ST", expectedName: "Nordea Bank", indices: ["OMX SE 30"] },
]

// ─── Denmark — OMX Copenhagen 25 ───
const OMX_DK: TickerEntry[] = [
  { ticker: "NOVO-B.CO", expectedName: "Novo Nordisk B", indices: ["OMX DK 25"] },
  { ticker: "DSV.CO", expectedName: "DSV", indices: ["OMX DK 25"] },
  { ticker: "CARL-B.CO", expectedName: "Carlsberg B", indices: ["OMX DK 25"] },
  { ticker: "NZYM-B.CO", expectedName: "Novozymes B", indices: ["OMX DK 25"] },
  { ticker: "ORSTED.CO", expectedName: "Ørsted", indices: ["OMX DK 25"] },
  { ticker: "COLO-B.CO", expectedName: "Coloplast B", indices: ["OMX DK 25"] },
  { ticker: "DEMANT.CO", expectedName: "Demant", indices: ["OMX DK 25"] },
  { ticker: "GN.CO", expectedName: "GN Store Nord", indices: ["OMX DK 25"] },
  { ticker: "MAERSK-B.CO", expectedName: "A.P. Møller-Mærsk B", indices: ["OMX DK 25"] },
  { ticker: "ISS.CO", expectedName: "ISS", indices: ["OMX DK 25"] },
  { ticker: "TRYG.CO", expectedName: "Tryg", indices: ["OMX DK 25"] },
  { ticker: "VWS.CO", expectedName: "Vestas Wind Systems", indices: ["OMX DK 25"] },
  { ticker: "GMAB.CO", expectedName: "Genmab", indices: ["OMX DK 25"] },
  { ticker: "AMBU-B.CO", expectedName: "Ambu B", indices: ["OMX DK 25"] },
  { ticker: "PNDORA.CO", expectedName: "Pandora", indices: ["OMX DK 25"] },
  { ticker: "FLS.CO", expectedName: "FLSmidth", indices: ["OMX DK 25"] },
  { ticker: "RBREW.CO", expectedName: "Royal Unibrew", indices: ["OMX DK 25"] },
]

// ─── Norway — OBX 25 ───
const OBX_NO: TickerEntry[] = [
  { ticker: "EQNR.OL", expectedName: "Equinor", indices: ["OBX 25"] },
  { ticker: "DNB.OL", expectedName: "DNB Bank", indices: ["OBX 25"] },
  { ticker: "TEL.OL", expectedName: "Telenor", indices: ["OBX 25"] },
  { ticker: "MOWI.OL", expectedName: "Mowi", indices: ["OBX 25"] },
  { ticker: "YAR.OL", expectedName: "Yara International", indices: ["OBX 25"] },
  { ticker: "ORK.OL", expectedName: "Orkla", indices: ["OBX 25"] },
  { ticker: "AKERBP.OL", expectedName: "Aker BP", indices: ["OBX 25"] },
  { ticker: "SALM.OL", expectedName: "SalMar", indices: ["OBX 25"] },
  { ticker: "NHY.OL", expectedName: "Norsk Hydro", indices: ["OBX 25"] },
  { ticker: "GJFS.OL", expectedName: "Gjensidige Forsikring", indices: ["OBX 25"] },
  { ticker: "STB.OL", expectedName: "Storebrand", indices: ["OBX 25"] },
  { ticker: "SUBC.OL", expectedName: "Subsea 7", indices: ["OBX 25"] },
  { ticker: "AKER.OL", expectedName: "Aker ASA", indices: ["OBX 25"] },
  { ticker: "MPCC.OL", expectedName: "MPC Container Ships", indices: ["OBX 25"] },
  { ticker: "KAHOT.OL", expectedName: "Kahoot!", indices: ["OBX 25"] },
]

// ─── Germany — MDAX selection (30 key mid-caps) ───
const MDAX: TickerEntry[] = [
  { ticker: "ZAL.DE", expectedName: "Zalando", indices: ["MDAX"] },
  { ticker: "TUI1.DE", expectedName: "TUI AG", indices: ["MDAX"] },
  { ticker: "TKA.DE", expectedName: "ThyssenKrupp", indices: ["MDAX"] },
  { ticker: "SDF.DE", expectedName: "K+S AG", indices: ["MDAX"] },
  { ticker: "QIA.DE", expectedName: "QIAGEN", indices: ["MDAX"] },
  { ticker: "NEM.DE", expectedName: "Nemetschek", indices: ["MDAX"] },
  { ticker: "KGX.DE", expectedName: "KION Group", indices: ["MDAX"] },
  { ticker: "BOSS.DE", expectedName: "Hugo Boss", indices: ["MDAX"] },
  { ticker: "HOT.DE", expectedName: "Hochtief", indices: ["MDAX"] },
  { ticker: "G1A.DE", expectedName: "GEA Group", indices: ["MDAX"] },
  { ticker: "EVD.DE", expectedName: "CTS Eventim", indices: ["MDAX"] },
  { ticker: "DUE.DE", expectedName: "Dürr AG", indices: ["MDAX"] },
  { ticker: "BC8.DE", expectedName: "Bechtle", indices: ["MDAX"] },
  { ticker: "AFX.DE", expectedName: "Carl Zeiss Meditec", indices: ["MDAX"] },
  { ticker: "PUM.DE", expectedName: "Puma SE", indices: ["MDAX"] },
  { ticker: "RAA.DE", expectedName: "Rational AG", indices: ["MDAX"] },
  { ticker: "LEG.DE", expectedName: "LEG Immobilien", indices: ["MDAX"] },
  { ticker: "FNTN.DE", expectedName: "freenet AG", indices: ["MDAX"] },
  { ticker: "ECV.DE", expectedName: "Encavis AG", indices: ["MDAX"] },
  { ticker: "GXI.DE", expectedName: "Gerresheimer", indices: ["MDAX"] },
  { ticker: "KRN.DE", expectedName: "Krones AG", indices: ["MDAX"] },
  { ticker: "NDX1.DE", expectedName: "Nordex SE", indices: ["MDAX"] },
  { ticker: "WAF.DE", expectedName: "Siltronic AG", indices: ["MDAX"] },
  { ticker: "WCH.DE", expectedName: "Wacker Chemie", indices: ["MDAX"] },
  { ticker: "TMV.DE", expectedName: "TeamViewer", indices: ["MDAX"] },
  { ticker: "G24.DE", expectedName: "Scout24", indices: ["MDAX"] },
  { ticker: "HAG.DE", expectedName: "Hensoldt AG", indices: ["MDAX"] },
  { ticker: "SZG.DE", expectedName: "Salzgitter AG", indices: ["MDAX"] },
  { ticker: "DWS.DE", expectedName: "DWS Group", indices: ["MDAX"] },
  { ticker: "EVK.DE", expectedName: "Evonik Industries", indices: ["MDAX"] },
]

// ─── USA — S&P 500 next 150 (après le top 100) ───
const SP500_NEXT: TickerEntry[] = [
  { ticker: "KLAC", expectedName: "KLA Corporation", indices: ["S&P 500"] },
  { ticker: "MCO", expectedName: "Moody's", indices: ["S&P 500"] },
  { ticker: "FTNT", expectedName: "Fortinet", indices: ["S&P 500"] },
  { ticker: "ETN", expectedName: "Eaton Corporation", indices: ["S&P 500"] },
  { ticker: "TDG", expectedName: "TransDigm Group", indices: ["S&P 500"] },
  { ticker: "MPWR", expectedName: "Monolithic Power Systems", indices: ["S&P 500"] },
  { ticker: "FICO", expectedName: "Fair Isaac (FICO)", indices: ["S&P 500"] },
  { ticker: "ON", expectedName: "ON Semiconductor", indices: ["S&P 500"] },
  { ticker: "NXPI", expectedName: "NXP Semiconductors", indices: ["S&P 500"] },
  { ticker: "MRVL", expectedName: "Marvell Technology", indices: ["S&P 500"] },
  { ticker: "WDAY", expectedName: "Workday", indices: ["S&P 500"] },
  { ticker: "VEEV", expectedName: "Veeva Systems", indices: ["S&P 500"] },
  { ticker: "DXCM", expectedName: "DexCom", indices: ["S&P 500"] },
  { ticker: "IDXX", expectedName: "IDEXX Laboratories", indices: ["S&P 500"] },
  { ticker: "TT", expectedName: "Trane Technologies", indices: ["S&P 500"] },
  { ticker: "BX", expectedName: "Blackstone", indices: ["S&P 500"] },
  { ticker: "APH", expectedName: "Amphenol", indices: ["S&P 500"] },
  { ticker: "AMP", expectedName: "Ameriprise Financial", indices: ["S&P 500"] },
  { ticker: "ADP", expectedName: "Automatic Data Processing", indices: ["S&P 500"] },
  { ticker: "PAYX", expectedName: "Paychex", indices: ["S&P 500"] },
  { ticker: "FIS", expectedName: "Fidelity National Information", indices: ["S&P 500"] },
  { ticker: "GPN", expectedName: "Global Payments", indices: ["S&P 500"] },
  { ticker: "TROW", expectedName: "T. Rowe Price", indices: ["S&P 500"] },
  { ticker: "MET", expectedName: "MetLife", indices: ["S&P 500"] },
  { ticker: "AIG", expectedName: "American International Group", indices: ["S&P 500"] },
  { ticker: "TRV", expectedName: "Travelers Companies", indices: ["S&P 500"] },
  { ticker: "ALL", expectedName: "Allstate", indices: ["S&P 500"] },
  { ticker: "HIG", expectedName: "Hartford Financial Services", indices: ["S&P 500"] },
  { ticker: "PFG", expectedName: "Principal Financial Group", indices: ["S&P 500"] },
  { ticker: "AFL", expectedName: "Aflac", indices: ["S&P 500"] },
  { ticker: "RF", expectedName: "Regions Financial", indices: ["S&P 500"] },
  { ticker: "CFG", expectedName: "Citizens Financial Group", indices: ["S&P 500"] },
  { ticker: "HBAN", expectedName: "Huntington Bancshares", indices: ["S&P 500"] },
  { ticker: "KEY", expectedName: "KeyCorp", indices: ["S&P 500"] },
  { ticker: "FITB", expectedName: "Fifth Third Bancorp", indices: ["S&P 500"] },
  { ticker: "MTB", expectedName: "M&T Bank", indices: ["S&P 500"] },
  { ticker: "USB", expectedName: "U.S. Bancorp", indices: ["S&P 500"] },
  { ticker: "TFC", expectedName: "Truist Financial", indices: ["S&P 500"] },
  { ticker: "STT", expectedName: "State Street", indices: ["S&P 500"] },
  { ticker: "BK", expectedName: "Bank of New York Mellon", indices: ["S&P 500"] },
  { ticker: "NTRS", expectedName: "Northern Trust", indices: ["S&P 500"] },
  { ticker: "PSA", expectedName: "Public Storage", indices: ["S&P 500"] },
  { ticker: "WELL", expectedName: "Welltower", indices: ["S&P 500"] },
  { ticker: "VTR", expectedName: "Ventas", indices: ["S&P 500"] },
  { ticker: "EQR", expectedName: "Equity Residential", indices: ["S&P 500"] },
  { ticker: "AVB", expectedName: "AvalonBay Communities", indices: ["S&P 500"] },
  { ticker: "ESS", expectedName: "Essex Property Trust", indices: ["S&P 500"] },
  { ticker: "O", expectedName: "Realty Income", indices: ["S&P 500"] },
  { ticker: "VICI", expectedName: "VICI Properties", indices: ["S&P 500"] },
  { ticker: "IRM", expectedName: "Iron Mountain", indices: ["S&P 500"] },
  { ticker: "EXR", expectedName: "Extra Space Storage", indices: ["S&P 500"] },
  { ticker: "MAA", expectedName: "Mid-America Apartment", indices: ["S&P 500"] },
  { ticker: "DLR", expectedName: "Digital Realty Trust", indices: ["S&P 500"] },
  { ticker: "EQIX", expectedName: "Equinix", indices: ["S&P 500"] },
  { ticker: "CCI", expectedName: "Crown Castle", indices: ["S&P 500"] },
  { ticker: "SBAC", expectedName: "SBA Communications", indices: ["S&P 500"] },
  { ticker: "HST", expectedName: "Host Hotels & Resorts", indices: ["S&P 500"] },
  { ticker: "KIM", expectedName: "Kimco Realty", indices: ["S&P 500"] },
  { ticker: "REG", expectedName: "Regency Centers", indices: ["S&P 500"] },
  { ticker: "FRT", expectedName: "Federal Realty Investment", indices: ["S&P 500"] },
  { ticker: "SPG", expectedName: "Simon Property Group", indices: ["S&P 500"] },
  { ticker: "CMG", expectedName: "Chipotle Mexican Grill", indices: ["S&P 500"] },
  { ticker: "MAR", expectedName: "Marriott International", indices: ["S&P 500"] },
  { ticker: "HLT", expectedName: "Hilton Worldwide", indices: ["S&P 500"] },
  { ticker: "LVS", expectedName: "Las Vegas Sands", indices: ["S&P 500"] },
  { ticker: "WYNN", expectedName: "Wynn Resorts", indices: ["S&P 500"] },
  { ticker: "MGM", expectedName: "MGM Resorts", indices: ["S&P 500"] },
  { ticker: "CCL", expectedName: "Carnival Corporation", indices: ["S&P 500"] },
  { ticker: "RCL", expectedName: "Royal Caribbean Group", indices: ["S&P 500"] },
  { ticker: "NCLH", expectedName: "Norwegian Cruise Line", indices: ["S&P 500"] },
  { ticker: "DAL", expectedName: "Delta Air Lines", indices: ["S&P 500"] },
  { ticker: "UAL", expectedName: "United Airlines", indices: ["S&P 500"] },
  { ticker: "AAL", expectedName: "American Airlines", indices: ["S&P 500"] },
  { ticker: "LUV", expectedName: "Southwest Airlines", indices: ["S&P 500"] },
  { ticker: "JBHT", expectedName: "J.B. Hunt Transport", indices: ["S&P 500"] },
  { ticker: "ODFL", expectedName: "Old Dominion Freight Line", indices: ["S&P 500"] },
  { ticker: "XPO", expectedName: "XPO", indices: ["S&P 500"] },
  { ticker: "EXPD", expectedName: "Expeditors International", indices: ["S&P 500"] },
  { ticker: "CHRW", expectedName: "C.H. Robinson", indices: ["S&P 500"] },
  { ticker: "RSG", expectedName: "Republic Services", indices: ["S&P 500"] },
  { ticker: "WM", expectedName: "Waste Management", indices: ["S&P 500"] },
  { ticker: "CSGP", expectedName: "CoStar Group", indices: ["S&P 500"] },
  { ticker: "MSCI", expectedName: "MSCI", indices: ["S&P 500"] },
  { ticker: "NDAQ", expectedName: "Nasdaq Inc.", indices: ["S&P 500"] },
  { ticker: "ICE", expectedName: "Intercontinental Exchange", indices: ["S&P 500"] },
  { ticker: "CBOE", expectedName: "Cboe Global Markets", indices: ["S&P 500"] },
  { ticker: "BR", expectedName: "Broadridge Financial", indices: ["S&P 500"] },
  { ticker: "NTAP", expectedName: "NetApp", indices: ["S&P 500"] },
  { ticker: "AKAM", expectedName: "Akamai Technologies", indices: ["S&P 500"] },
  { ticker: "CDNS", expectedName: "Cadence Design Systems", indices: ["S&P 500"] },
  { ticker: "SNPS", expectedName: "Synopsys", indices: ["S&P 500"] },
  { ticker: "ANSS", expectedName: "Ansys", indices: ["S&P 500"] },
  { ticker: "PTC", expectedName: "PTC Inc.", indices: ["S&P 500"] },
  { ticker: "TRMB", expectedName: "Trimble", indices: ["S&P 500"] },
  { ticker: "ZBRA", expectedName: "Zebra Technologies", indices: ["S&P 500"] },
  { ticker: "TYL", expectedName: "Tyler Technologies", indices: ["S&P 500"] },
  { ticker: "PAYC", expectedName: "Paycom Software", indices: ["S&P 500"] },
  { ticker: "PCTY", expectedName: "Paylocity", indices: ["S&P 500"] },
  { ticker: "HUBS", expectedName: "HubSpot", indices: ["S&P 500"] },
  { ticker: "ZI", expectedName: "ZoomInfo Technologies", indices: ["S&P 500"] },
  { ticker: "DDOG", expectedName: "Datadog", indices: ["S&P 500"] },
  { ticker: "SNOW", expectedName: "Snowflake", indices: ["S&P 500"] },
  { ticker: "MDB", expectedName: "MongoDB", indices: ["S&P 500"] },
  { ticker: "NET", expectedName: "Cloudflare", indices: ["S&P 500"] },
  { ticker: "OKTA", expectedName: "Okta", indices: ["S&P 500"] },
  { ticker: "TWLO", expectedName: "Twilio", indices: ["S&P 500"] },
  { ticker: "ESTC", expectedName: "Elastic", indices: ["S&P 500"] },
  { ticker: "CFLT", expectedName: "Confluent", indices: ["S&P 500"] },
  { ticker: "ABNB", expectedName: "Airbnb", indices: ["S&P 500"] },
  { ticker: "DASH", expectedName: "DoorDash", indices: ["S&P 500"] },
  { ticker: "UBER", expectedName: "Uber Technologies", indices: ["S&P 500"] },
  { ticker: "LYFT", expectedName: "Lyft", indices: ["S&P 500"] },
  { ticker: "RBLX", expectedName: "Roblox", indices: ["S&P 500"] },
  { ticker: "EA", expectedName: "Electronic Arts", indices: ["S&P 500"] },
  { ticker: "TTWO", expectedName: "Take-Two Interactive", indices: ["S&P 500"] },
  { ticker: "ATVI", expectedName: "Activision Blizzard", indices: ["S&P 500"] },
  { ticker: "MTCH", expectedName: "Match Group", indices: ["S&P 500"] },
  { ticker: "IAC", expectedName: "IAC", indices: ["S&P 500"] },
  { ticker: "Z", expectedName: "Zillow Group", indices: ["S&P 500"] },
  { ticker: "OPEN", expectedName: "Opendoor Technologies", indices: ["S&P 500"] },
  { ticker: "NEM", expectedName: "Newmont", indices: ["S&P 500"] },
  { ticker: "FCX", expectedName: "Freeport-McMoRan", indices: ["S&P 500"] },
  { ticker: "NUE", expectedName: "Nucor", indices: ["S&P 500"] },
  { ticker: "CLF", expectedName: "Cleveland-Cliffs", indices: ["S&P 500"] },
  { ticker: "X", expectedName: "United States Steel", indices: ["S&P 500"] },
  { ticker: "AA", expectedName: "Alcoa", indices: ["S&P 500"] },
  { ticker: "CF", expectedName: "CF Industries", indices: ["S&P 500"] },
  { ticker: "MOS", expectedName: "Mosaic Company", indices: ["S&P 500"] },
  { ticker: "FMC", expectedName: "FMC Corporation", indices: ["S&P 500"] },
  { ticker: "LYB", expectedName: "LyondellBasell", indices: ["S&P 500"] },
  { ticker: "HUN", expectedName: "Huntsman Corporation", indices: ["S&P 500"] },
  { ticker: "CE", expectedName: "Celanese", indices: ["S&P 500"] },
  { ticker: "EMN", expectedName: "Eastman Chemical", indices: ["S&P 500"] },
  { ticker: "PPG", expectedName: "PPG Industries", indices: ["S&P 500"] },
  { ticker: "RPM", expectedName: "RPM International", indices: ["S&P 500"] },
  { ticker: "SHW", expectedName: "Sherwin-Williams", indices: ["S&P 500"] },
  { ticker: "OXY", expectedName: "Occidental Petroleum", indices: ["S&P 500"] },
  { ticker: "DVN", expectedName: "Devon Energy", indices: ["S&P 500"] },
  { ticker: "FANG", expectedName: "Diamondback Energy", indices: ["S&P 500"] },
  { ticker: "MRO", expectedName: "Marathon Oil", indices: ["S&P 500"] },
  { ticker: "APA", expectedName: "APA Corporation", indices: ["S&P 500"] },
  { ticker: "HAL", expectedName: "Halliburton", indices: ["S&P 500"] },
  { ticker: "BKR", expectedName: "Baker Hughes", indices: ["S&P 500"] },
  { ticker: "VLO", expectedName: "Valero Energy", indices: ["S&P 500"] },
  { ticker: "MPC", expectedName: "Marathon Petroleum", indices: ["S&P 500"] },
  { ticker: "PSX", expectedName: "Phillips 66", indices: ["S&P 500"] },
  { ticker: "DG", expectedName: "Dollar General", indices: ["S&P 500"] },
  { ticker: "DLTR", expectedName: "Dollar Tree", indices: ["S&P 500"] },
  { ticker: "ROST", expectedName: "Ross Stores", indices: ["S&P 500"] },
  { ticker: "TJX", expectedName: "TJX Companies", indices: ["S&P 500"] },
  { ticker: "GPS", expectedName: "Gap", indices: ["S&P 500"] },
  { ticker: "RL", expectedName: "Ralph Lauren", indices: ["S&P 500"] },
  { ticker: "PVH", expectedName: "PVH Corp", indices: ["S&P 500"] },
  { ticker: "HBI", expectedName: "Hanesbrands", indices: ["S&P 500"] },
  { ticker: "VFC", expectedName: "VF Corporation", indices: ["S&P 500"] },
  { ticker: "NKE", expectedName: "Nike", indices: ["S&P 500"] },
  { ticker: "LULU", expectedName: "Lululemon Athletica", indices: ["S&P 500"] },
  { ticker: "COLM", expectedName: "Columbia Sportswear", indices: ["S&P 500"] },
  { ticker: "EL", expectedName: "Estée Lauder", indices: ["S&P 500"] },
  { ticker: "COTY", expectedName: "Coty", indices: ["S&P 500"] },
  { ticker: "CHD", expectedName: "Church & Dwight", indices: ["S&P 500"] },
  { ticker: "CLX", expectedName: "Clorox", indices: ["S&P 500"] },
  { ticker: "CL", expectedName: "Colgate-Palmolive", indices: ["S&P 500"] },
  { ticker: "KMB", expectedName: "Kimberly-Clark", indices: ["S&P 500"] },
  { ticker: "GIS", expectedName: "General Mills", indices: ["S&P 500"] },
  { ticker: "K", expectedName: "Kellanova (Kellogg's)", indices: ["S&P 500"] },
  { ticker: "CPB", expectedName: "Campbell Soup", indices: ["S&P 500"] },
  { ticker: "HRL", expectedName: "Hormel Foods", indices: ["S&P 500"] },
  { ticker: "TSN", expectedName: "Tyson Foods", indices: ["S&P 500"] },
  { ticker: "SJM", expectedName: "J.M. Smucker", indices: ["S&P 500"] },
  { ticker: "MKC", expectedName: "McCormick & Company", indices: ["S&P 500"] },
  { ticker: "HSY", expectedName: "Hershey Company", indices: ["S&P 500"] },
]

// ─── France — CAC Mid 60 complément (tickers vérifiés) ───
const CAC_MID60_EXTRA: TickerEntry[] = [
  { ticker: "SPIE.PA", expectedName: "SPIE", indices: ["CAC Mid 60"] },
  { ticker: "BB.PA", expectedName: "Société BIC", indices: ["CAC Mid 60"] },      // BIC = BB sur Euronext
  { ticker: "ARG.PA", expectedName: "Argan", indices: ["CAC Mid 60"] },
  { ticker: "VCT.PA", expectedName: "Vicat", indices: ["CAC Mid 60"] },
  { ticker: "GLO.PA", expectedName: "GL Events", indices: ["CAC Mid 60"] },
  { ticker: "JCQ.PA", expectedName: "Jacquet Metals", indices: ["CAC Mid 60"] },
  { ticker: "LNA.PA", expectedName: "LNA Santé", indices: ["CAC Mid 60"] },
  { ticker: "KORI.PA", expectedName: "Clariane", indices: ["CAC Mid 60"] },        // ex-Korian
  { ticker: "SII.PA", expectedName: "SII Group", indices: ["CAC Mid 60"] },
  { ticker: "ASY.PA", expectedName: "Assystem", indices: ["CAC Mid 60"] },
  { ticker: "DLTA.PA", expectedName: "Delta Plus Group", indices: ["CAC Mid 60"] },
  { ticker: "BOI.PA", expectedName: "Boiron", indices: ["CAC Mid 60"] },
  { ticker: "HEXA.PA", expectedName: "Hexaom", indices: ["CAC Mid 60"] },
  { ticker: "TRO.PA", expectedName: "Tarkett", indices: ["CAC Mid 60"] },
  { ticker: "ELIOR.PA", expectedName: "Elior Group", indices: ["CAC Mid 60"] },
  { ticker: "MERY.PA", expectedName: "Mercialys", indices: ["CAC Mid 60"] },
  { ticker: "TOUR.PA", expectedName: "Société de la Tour Eiffel", indices: ["CAC Mid 60"] },
  { ticker: "FII.PA", expectedName: "Lisi", indices: ["CAC Mid 60"] },             // Lisi = FII sur Euronext
  { ticker: "TRI.PA", expectedName: "Trigano", indices: ["CAC Mid 60"] },
  { ticker: "MTU.PA", expectedName: "Manitou BF", indices: ["CAC Mid 60"] },
  { ticker: "CTRG.PA", expectedName: "Catering International", indices: ["CAC Mid 60"] },
  { ticker: "CEN.PA", expectedName: "Groupe Crit", indices: ["CAC Mid 60"] },
]

// ─── France — SBF 250 + autres valeurs SRD ───
const SRD_EXTRA: TickerEntry[] = [
  // Grandes caps hors SBF 120
  { ticker: "AMUN.PA", expectedName: "Amundi", indices: ["SBF 250"] },
  { ticker: "ADP.PA", expectedName: "Groupe ADP", indices: ["SBF 250"] },
  { ticker: "FR.PA", expectedName: "Valeo", indices: ["SBF 250"] },               // Valeo = FR sur Euronext
  { ticker: "ICAD.PA", expectedName: "Icade", indices: ["SBF 250"] },
  { ticker: "DEC.PA", expectedName: "JCDecaux", indices: ["SBF 250"] },
  { ticker: "ILD.PA", expectedName: "Iliad", indices: ["SBF 250"] },
  { ticker: "RF.PA", expectedName: "Eurazeo", indices: ["SBF 250"] },
  { ticker: "COFA.PA", expectedName: "Coface", indices: ["SBF 250"] },
  { ticker: "FFP.PA", expectedName: "Établissements Peugeot Frères", indices: ["SBF 250"] },
  { ticker: "ALTA.PA", expectedName: "Altarea", indices: ["SBF 250"] },
  { ticker: "ATE.PA", expectedName: "Alten", indices: ["SBF 250"] },
  { ticker: "MMT.PA", expectedName: "M6 Métropole Télévision", indices: ["SBF 250"] },
  { ticker: "BON.PA", expectedName: "Bonduelle", indices: ["SBF 250"] },
  { ticker: "ELIS.PA", expectedName: "Elis", indices: ["SBF 250"] },
  { ticker: "ETL.PA", expectedName: "Eutelsat", indices: ["SBF 250"] },
  { ticker: "ROTH.PA", expectedName: "Rothschild & Co", indices: ["SBF 250"] },
  { ticker: "CDI.PA", expectedName: "Christian Dior", indices: ["SBF 250"] },
  { ticker: "ENX.PA", expectedName: "Euronext", indices: ["SBF 250"] },
  { ticker: "SAVE.PA", expectedName: "Savencia", indices: ["SBF 250"] },
  { ticker: "SCHP.PA", expectedName: "Séché Environnement", indices: ["SBF 250"] },
  { ticker: "RE.PA", expectedName: "Colas", indices: ["SBF 250"] },
  { ticker: "PHA.PA", expectedName: "Equasens", indices: ["SBF 250"] },
  // Finance
  { ticker: "ABCA.PA", expectedName: "ABC Arbitrage", indices: ["SBF 250"] },
  { ticker: "LTA.PA", expectedName: "Altamir", indices: ["SBF 250"] },
  { ticker: "CDA.PA", expectedName: "Compagnie des Alpes", indices: ["SBF 250"] },
  { ticker: "SOF.PA", expectedName: "Société Foncière Lyonnaise", indices: [] },
  // Industrie / Environnement
  { ticker: "MRN.PA", expectedName: "Mersen", indices: ["SBF 250"] },
  { ticker: "BEN.PA", expectedName: "Beneteau", indices: ["SBF 250"] },
  { ticker: "CRI.PA", expectedName: "Chargeurs", indices: ["SBF 250"] },
  { ticker: "EXE.PA", expectedName: "Exel Industries", indices: ["SBF 250"] },
  { ticker: "GOE.PA", expectedName: "Exail Technologies", indices: ["SBF 250"] },
  { ticker: "AKW.PA", expectedName: "Akwel", indices: ["SBF 250"] },
  { ticker: "PIG.PA", expectedName: "Haulotte Group", indices: [] },
  { ticker: "STF.PA", expectedName: "STEF", indices: ["SBF 250"] },
  { ticker: "DBG.PA", expectedName: "Derichebourg", indices: ["SBF 250"] },
  { ticker: "SDG.PA", expectedName: "Synergie", indices: ["SBF 250"] },
  { ticker: "MAU.PA", expectedName: "Maurel et Prom", indices: [] },
  // IT / Tech
  { ticker: "LDLC.PA", expectedName: "LDLC Group", indices: ["SBF 250"] },
  { ticker: "AURES.PA", expectedName: "Aurès Technologies", indices: [] },
  { ticker: "VU.PA", expectedName: "Vusiongroup", indices: ["SBF 250"] },          // ex-SES-imagotag
  { ticker: "AXW.PA", expectedName: "Axway Software", indices: ["SBF 250"] },
  { ticker: "SWP.PA", expectedName: "Sword Group", indices: [] },
  // Agroalimentaire / Luxe
  { ticker: "ITP.PA", expectedName: "Interparfums", indices: ["SBF 250"] },
  { ticker: "LPE.PA", expectedName: "Laurent-Perrier", indices: [] },
  { ticker: "MAN.PA", expectedName: "Manutan International", indices: [] },
  { ticker: "VINCI.PA", expectedName: "Vilmorin & Cie", indices: ["SBF 250"] },    // Vilmorin ≠ Vinci
  // Telecom / Services
  { ticker: "IAM.PA", expectedName: "Maroc Telecom", indices: [] },
  { ticker: "LSS.PA", expectedName: "Lectra", indices: ["SBF 250"] },
  { ticker: "ATI.PA", expectedName: "Actia Group", indices: [] },
  { ticker: "MND.PA", expectedName: "MND Group", indices: [] },
  { ticker: "HDF.PA", expectedName: "Hydrogène de France", indices: [] },
  { ticker: "ODET.PA", expectedName: "Financière de l'Odet", indices: [] },
  { ticker: "PWG.PA", expectedName: "Prodways Group", indices: ["SBF 250"] },
  { ticker: "FGA.PA", expectedName: "Figeac Aéro", indices: ["SBF 250"] },
  { ticker: "CARM.PA", expectedName: "Carmila", indices: ["SBF 250"] },
  { ticker: "SESG.PA", expectedName: "SES", indices: ["SBF 250"] },
  { ticker: "TE.PA", expectedName: "Technip Energies", indices: ["CAC 40"] },
  { ticker: "VK.PA", expectedName: "Vallourec", indices: ["SBF 250"] },
  { ticker: "AB.PA", expectedName: "AB Science", indices: [] },
  { ticker: "DBV.PA", expectedName: "DBV Technologies", indices: [] },
]

// ─── USA — Grandes caps récentes (post-2023, manquantes) ───
const SP500_RECENT: TickerEntry[] = [
  // Méga-caps tech absentes
  { ticker: "PLTR", expectedName: "Palantir Technologies", indices: ["S&P 500"] },
  { ticker: "ARM", expectedName: "Arm Holdings", indices: ["S&P 500"] },
  { ticker: "CRWD", expectedName: "CrowdStrike Holdings", indices: ["S&P 500", "Nasdaq 100"] },
  { ticker: "ANET", expectedName: "Arista Networks", indices: ["S&P 500"] },
  { ticker: "APP", expectedName: "AppLovin", indices: ["Nasdaq 100"] },
  { ticker: "SMCI", expectedName: "Super Micro Computer", indices: ["S&P 500"] },
  // Énergie / Infrastructure
  { ticker: "GEV", expectedName: "GE Vernova", indices: ["S&P 500"] },
  { ticker: "CEG", expectedName: "Constellation Energy", indices: ["S&P 500"] },
  { ticker: "VST", expectedName: "Vistra", indices: ["S&P 500"] },
  // Hardware / PC
  { ticker: "DELL", expectedName: "Dell Technologies", indices: ["S&P 500"] },
  { ticker: "HPQ", expectedName: "HP Inc.", indices: ["S&P 500"] },
  { ticker: "HPE", expectedName: "Hewlett Packard Enterprise", indices: ["S&P 500"] },
  // Finance / Crypto
  { ticker: "COIN", expectedName: "Coinbase Global", indices: ["S&P 500"] },
  { ticker: "SQ", expectedName: "Block Inc.", indices: ["S&P 500"] },
  { ticker: "AFRM", expectedName: "Affirm Holdings", indices: ["Nasdaq 100"] },
  // Cybersécurité / SaaS
  { ticker: "AXON", expectedName: "Axon Enterprise", indices: ["S&P 500"] },
  { ticker: "ZS", expectedName: "Zscaler", indices: ["Nasdaq 100"] },
  { ticker: "TEAM", expectedName: "Atlassian", indices: ["Nasdaq 100"] },
  { ticker: "GTLB", expectedName: "GitLab", indices: [] },
  { ticker: "SAMSF", expectedName: "Samsara", indices: [] },
  { ticker: "IOT", expectedName: "Samsara Inc.", indices: ["S&P 500"] },
  // Consommation / Streaming
  { ticker: "SHOP", expectedName: "Shopify", indices: ["S&P 500"] },
  { ticker: "SPOT", expectedName: "Spotify Technology", indices: [] },
  // EV / Mobilité
  { ticker: "RIVN", expectedName: "Rivian Automotive", indices: ["Nasdaq 100"] },
  { ticker: "LCID", expectedName: "Lucid Group", indices: [] },
  // Autres Nasdaq 100 manquants
  { ticker: "MELI", expectedName: "MercadoLibre", indices: ["Nasdaq 100"] },
  { ticker: "CPNG", expectedName: "Coupang", indices: ["S&P 500"] },
  { ticker: "NU", expectedName: "Nu Holdings", indices: ["S&P 500"] },
  { ticker: "HOOD", expectedName: "Robinhood Markets", indices: [] },
]

// ─── Merge & deduplicate ───

function buildUniverse(): TickerEntry[] {
  const all = [
    ...CAC40, ...CAC_NEXT20, ...CAC_MID60, ...CAC_MID60_EXTRA,
    ...DAX40, ...MDAX, ...AEX25, ...BEL20, ...IBEX,
    ...ITALY, ...PORTUGAL, ...FINLAND, ...IRELAND, ...AUSTRIA,
    ...FTSE100,
    ...SMI,
    ...OMX_SE, ...OMX_DK, ...OBX_NO,
    ...SP500, ...SP500_NEXT, ...SP500_RECENT,
    ...CHINA_TOP100,
    ...JAPAN_TOP80,
    ...SRD_EXTRA,
  ]

  const map = new Map<string, TickerEntry>()
  for (const entry of all) {
    const existing = map.get(entry.ticker)
    if (existing) {
      const merged = new Set([...existing.indices, ...entry.indices])
      existing.indices = Array.from(merged)
    } else {
      map.set(entry.ticker, { ...entry, indices: [...entry.indices] })
    }
  }

  // Tag SBF 120 = CAC 40 + Next 20 + Mid 60
  for (const entry of map.values()) {
    if (
      entry.indices.includes("CAC 40") ||
      entry.indices.includes("CAC Next 20") ||
      entry.indices.includes("CAC Mid 60")
    ) {
      if (!entry.indices.includes("SBF 120")) {
        entry.indices.push("SBF 120")
      }
    }
  }

  return Array.from(map.values())
}

export const UNIVERSE = buildUniverse()

export const ALL_INDICES = [
  "CAC 40",
  "CAC Next 20",
  "CAC Mid 60",
  "SBF 120",
  "DAX 40",
  "MDAX",
  "AEX 25",
  "BEL 20",
  "IBEX 35",
  "FTSE 100",
  "SMI",
  "SMIM",
  "OMX SE 30",
  "OMX DK 25",
  "OBX 25",
  "S&P 500",
  "Chine Top 100",
  "Japon Top 100",
] as const

export type IndexName = (typeof ALL_INDICES)[number]
